### ISSUE TITLE
myocardial fiber currents

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#1163]
Please consider adding terms for:
abnormal myocardial fiber sodium channel current
abnormal myocardial fiber calcium channel current
J:183588 has the phenotype of reduced mean peak macroscopic voltage-gated Na+ current densities. I'm annotating this to abnormal myocardial fiber physiology (MP:0004215) for now. There are several (~20) existing annotations for abnormalities in either calcium channel or sodium channel currents so we may want to split these terms out.

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1163](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1163)

**Comment by sbello** [comment]
added terms
MP:0020345 
MP:0020346 calcium currents
MP:0020347 sodium currents
