### ISSUE TITLE
epithelial cell homeostasis

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#1192]
Hello,

Here is a term that I would need:

epithelial hyperplasia,  PMID:22042863

Thank you for your help,

Nevila Hyka-Nouspikel

Reported by: nnouspikel

Original Ticket: [obo/mammalian-phenotype-requests/1192](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1192)

**Comment by sbello** [comment]
hyperplastic - MP:0021108
hypoplastic - MP:0021109
