### ISSUE TITLE
spatial learning

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#125]
Can we do more to increase the alignment between MP and GO? The one specific xp we have is dodgy:

[Term]
id: MP:0001463 ! abnormal spatial learning
intersection_of: PATO:0000460 ! abnormal
intersection_of: inheres_in GO:0008542 ! visual learning

(supported by a non-exact synonym)

And everything else looks very different

(email, Chris Mungall 10/28/08)

Reported by: cindyJax

Original Ticket: "obo/mammalian-phenotype-requests/125":https://sourceforge.net/p/obo/mammalian-phenotype-requests/125

**Comment by sbello** [comment]
Most but not all MP terms use NBO terms in the axioms. Do we want to switch these to GO where possible? Currently MP:0011616 (abnormal nonassociative learning) and its children have GO in the axiom as does MP:0002063
