### ISSUE TITLE
infertility revisited

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#1389]
consider new infertility definition: 

inability of male/female to produce offspring after successful mating behavior

or 

Diminished or absent ability to conceive (in females) and bear offspring (males and females). 

crux of the problem is whether to include mating behavior as part of infertility or not (but do not think this is appropriate).

We have mouse descriptions that simply state that no offspring were produced from crosses without any further info on whether successful mating occurred or not. 

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/1389](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1389)

**Comment by sbello** [comment]
@anna-anagnostop  please review this as part of the infertility project

**Comment by anna-anagnostop** [comment]
Added "physiological" to infertility textual definition.
Also, added comment: This term is independent of any anomalies in mating behavior. Consider using abnormal sexual interaction MP:0002566 when anomalies in mating behavior are observed.
