### ISSUE TITLE
increased kidney epithelial primary cilium length

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#2202]
I'd like to see "increased kidney epithelial primary cilium length" added as a child of "abnormal kidney epithelial cell primary cilium morphology" (MP:0011065).  The definition could be "increased length of the cilia on cells of the renal tubule or collecting duct."  An example can be found in PMID:19515853.

**Comment by sbello** [comment]
increased length - MP:0020382
decreased length - MP:0020383
absent - MP:0020384
