### ISSUE TITLE
increased and decreased cardiac muscle relaxation 

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#2229]
I would like to see "increased cardiac muscle relaxation" and "decreased cardiac muscle relaxation" added to the MP ontology under the parent term "abnormal cardiac muscle relaxation” (MP:0004084). The definitions could be "greater than the normal ability of the cardiac/heart muscle to lengthen following contractions, often measured by dP/dt min" and “inability or reduced ability of the cardiac/heart muscle to lengthen following contractions, often measured by dP/dt min”.  An example can be found in PMID:11565821.

**Comment by sbello** [comment]
increased MP:0020418
decreased MP:0020418
