### ISSUE TITLE
increased kindling response

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#2241]
I would like to see "increased kindling response” added to the MP ontology under the parent term "abnormal kindling response” (MP:0001499).  The definition could be "an increase in epileptogenic changes normally induced by daily sub threshold electrical brain stimulation".  An example can be found in PMID:27265781.  A synonym would be “increased kindling behavior".

**Comment by sbello** [comment]
MP:0020424
