### ISSUE TITLE
abnormal play behavior

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#2263]
This is a request for a new term.
>1. Preferred term label

"abnormal play behavior"

>2. Synonyms (e.g., absent spleen)
abnormal juvenile play behavior;
abnormal social play behavior

>3. Textual definition
deviation from the usual play behavior of tugging, wrestling, boxing, or chasing
PMID:24773431

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

>5. Suggested parent term

abnormal social/conspecific interaction (MP:0002557)

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as MGI:sbello (organization, first initial-last name)

RGD:gthayman

**Comment by sbello** [comment]
MP:0020437
