### ISSUE TITLE
rhinosinusitis

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#2297]
Add:
rhinosinusitis (a child of both sinus inflammation MP:0001872 AND rhinitis MP:0001867 )
DEF: local accumulation of fluid, plasma proteins, and leukocytes in the mucous membranes of the nose and in one or more paranasal sinuses
SOURCE: https://www.merriam-webster.com/medical/rhinosinusitis
J:185566
Anna

**Comment by anna-anagnostop** [comment]
rhinosinusitis MP:0030118

**Comment by anna-anagnostop** [comment]
Remove rhinosinusitis from under rhinitis

**Comment by sbello** [comment]
don't remove from rhinitis, term is inflammation of nasal and sinus membranes, so it should be under both
