### ISSUE TITLE
new term request: abnormal necroptosis

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#2669]
>1. Preferred term label 
**abnormal necroptosis**

>2. Synonyms
**abnormal programmed necrosis**

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID or URL(s) to refer to any relevant article(s) that provides information about the suggested term).
**any anomaly in the execution of immune-system-induced programmed necrosis**
https://en.wikipedia.org/wiki/Necroptosis

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**PMID:25751141**

>5. Suggested parent term
**MP:0000313 abnormal cell death**

**Comment by cmungall** [comment]
I recommend the same terminology as GO

```
[Term]
id: GO:0097528
name: execution phase of necroptosis
namespace: biological_process
def: "A stage of the necroptotic process that starts after a necroptotic signal has been relayed to the execution machinery. Key steps of the execution phase are swelling of organelles, minor ultrastructural modifications of the nucleus (specifically, dilatation of the nuclear membrane and condensation of chromatin into small, irregular, circumscribed patches) and increased cell volume (oncosis), culminating in the disruption of the plasma membrane and subsequent loss of intracellular contents. The execution phase ends when the cell has died." [GOC:mtg_apoptosis, PMID:20823910]
synonym: "execution phase of necroptotic process" EXACT []
synonym: "necroptosis" BROAD []
synonym: "necroptotic execution phase" EXACT []
is_a: GO:0044763  ! single-organism cellular process
relationship: part_of GO:0070266 ! necroptotic process
```

**Comment by sbello** [comment]
@cmungall Why would you suggest the execution phase rather than the more general 'necroptotic process' (GO:0070266)? My concern is curators may not be able to say for certain that the phenotype is part of the execution phases.

**Comment by sbello** [comment]
Handled in ticket #3897
