### ISSUE TITLE
greasy and oily skin terms

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#2746]
I just noticed that we have terms for both oily skin (MP:0001197 with 3 annotations, a child of shiny skin MP:0001196 ) and greasy skin (MP:0013144, with 0 annotations). One of them should be removed from the ontology and added as a synonym.
Anna

**Comment by anna-anagnostop** [comment]
Check with IMPC Ahmad_Retha as greasy skin is part of their subset. Is there a reason they did not use oily skin?

**Comment by sbello** [comment]
Will obsolete greasy skin with reference to oily skin as alternate term

**Comment by anna-anagnostop** [comment]
Done!

**Comment by anna-anagnostop** [comment]
"greasy skin" has been added as an exact synonym of oily skin MP:0001197
