### ISSUE TITLE
definitions not being displayed at MGI

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#2913]
Definitions for MP:0013945 and MP:0013932 are present in the OWL and OBO files but are not displayed on the MGI website. Anna and I can't see anything obviously wrong and the definitions display on the OLS site (but not Ontobee). I'm going to delete and reenter the definitions to see if this fixes the issue.

**Comment by anna-anagnostop** [comment]
Definitions for MP:0013945 and MP:0013932 are still not displayed on the MGI website as of 11/5/2018.

**Comment by sbello** [comment]
Trying deleting and reentering again but this time all the fields for MP:0013945

**Comment by sbello** [comment]
modified dbxrefs on MP:0005384 to see if that helps

**Comment by sbello** [comment]
removed dbxrefs on MP:0005384 to see if that helps

**Comment by anna-anagnostop** [comment]
One more example with definition not displayed on MGI site:
pancreatic acinus dilation MP:0014232
