### ISSUE TITLE
"abnormal white adipose tissue amount" (MP:0001781) parentage

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#3093]
The MP term "abnormal white adipose tissue amount" has children terms, some of which have "white" in the term and some do not.  Whether or not "white" is added to the children terms, the "decreased" terms could be changed to children of "decreased white adipose tissue amount" (MP:0001783), instead of their current placement as sibling terms of "decreased white adipose tissue amount" (MP:0001783). The argument for placement change could also be done for the "increased" terms.

**Comment by sbello** [comment]
Issue, is all adipose tissue in these tissues white or is it a mix of types. 
Uberon does not have subcutaneous adipose tissue or adipose tissue of abdominal region as child terms of white adipose tissue
I can't find any reference that asserts these are white adipose only.
Moved the terms out from under white adipose
