### ISSUE TITLE
new synonyms

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#3153]
The terms "decreased sensitivity to induced morbidity/mortality (MP:0009764) and "increased sensitivity to induced morbidity/mortality" (MP:0009763) are difficult to locate in the ontology.  Maybe the synonyms "increased survival from induced morbidity/mortality" and "decreased survival from induced morbidity/mortality" would be helpful.

**Comment by sbello** [comment]
added survival synonyms
