### ISSUE TITLE
new term request: thick retinal outer plexiform layer + thick retinal inner plexiform layer + long photoreceptor inner segment; plus rename and reorganization

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3256]
>1. Preferred term label 

**thick retinal outer plexiform layer**

**thick retinal inner plexiform layer**

**long photoreceptor inner segment**

>3. Textual definition 

**increased thickness of the retinal layer that is the site of synapses between the rods and cones (axons) and the horizontal and bipolar cells (dendrites)**

**increased thickness of the retinal cell layer where bipolar and amacrine cell axons synapse with ganglion cell dendrites**

**increased length of the photoreceptor region which contains the machinery of the cell (mitochondria, golgi, endoplasmic reticulum, etc) and where opsin molecules are assembled and passed to be part of the outer segment region**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**PMID:32093902 describes thick OPL in peripheral retina. Note that _thick retinal outer nuclear layer_ and _increased retinal inner nuclear layer thickness_ do exist. Obviously the latter needs to be renamed _thick retinal inner nuclear layer_ since it is a sibling of _thin retinal inner nuclear layer_. Also note that _long photoreceptor outer segment_ exists as a sibling of _short photoreceptor outer segment_ and _abnormal photoreceptor outer segment diameter_ with parent _abnormal photoreceptor outer segment size_. Maybe create a similar parent (_abnormal photoreceptor inner segment size_) for _long photoreceptor inner segment_ and _short photoreceptor inner segment_?**

>5. Suggested parent term 

**MP:0003732 _abnormal retinal outer plexiform layer morphology_**

**MP:0003734 _abnormal retinal inner plexiform layer morphology_**

**MP:0003730 _abnormal photoreceptor inner segment morphology_ or its to be created child _abnormal photoreceptor inner segment size_**

**Comment by sbello** [comment]
thick inner plexiform layer - MP:0014265
thick outer plexiform layer - MP:0014266
long photoreceptor inner segment - MP:0014247 (created earlier)
