### ISSUE TITLE
atretic ovarian follicle

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3304]
consider adding a term for 

increased atretic ovarian follicle number

syn: elevated atretic ovarian follicle number

definition: increase in the number of degenerated immature ovarian follicles 
see http://medcell.med.yale.edu/histology/female_reproductive_system_lab/atretic_follicle.php
https://www.sciencedirect.com/topics/medicine-and-dentistry/ovary-follicle-atresia 
phenotype in J:294607 also many annotations to MP:0008871

**Comment by anna-anagnostop** [comment]
ovarian follicle atresia GO:0001552 
DeF: A periodic process in which immature ovarian follicles degenerate and are subsequently re-absorbed.

**Comment by anna-anagnostop** [comment]
Added new term:
increased atretic ovarian follicle number MP:0031239 (as a child of abnormal ovarian follicle number MP:0008871)
