### ISSUE TITLE
new term request: abnormal perivascular vein cell coverage

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3307]
>1. Preferred term label

**abnormal perivascular vein cell coverage**

>2. Synonyms 

**abnormal PVC coverage**

>3. Textual definition 

**any structural anomaly of the cells residing around blood vessels, which includes vascular smooth muscle cells and pericytes**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

 **PMID:30571485 "defective PVC coverage"**

>5. Suggested parent term 

**MP:0002725 abnormal vein morphology**

**Comment by sbello** [comment]
modified the definition to "any anomaly in the extent to which the cells residing around veins surround the vessel, these cells include vascular smooth muscle cells and pericytes" as the proposed definition would be for 'abnormal perivascular cell morphology' rather than for coverage
