### ISSUE TITLE
new term request: increased/decreased spleen B cell follicle number

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3309]
>1. Preferred term label
**increased spleen B cell follicle number
decreased spleen B cell follicle number**

>2. Synonyms
**higher spleen B cell follicle number | enhanced spleen B cell follicle number
lower spleen B cell follicle number | reduced spleen B cell follicle number**

>3. Textual definition 
**greater number of the structures in the white pulp of the spleen where the affinity maturation of B cells and the generation of memory B cells and plasma cells occur
reduced number of the structures in the white pulp of the spleen where the affinity maturation of B cells and the generation of memory B cells and plasma cells occur**

>4. Any additional notes to clarify the meaning or use of the term.
**PMID:31296356
Also, MP:0002359 _abnormal spleen germinal center morphology_ does have increased/decreased number children....**

>5. Suggested parent term
MP:0008470 _abnormal spleen B cell follicle morphology_

**Comment by sbello** [comment]
abnormal - MP:0014261
increased - MP:0014262
decreased - MP:0014263
