### ISSUE TITLE
review hypoxia annotations

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3336]
related to https://github.com/obophenotype/upheno/issues/721

Most of the annotations to hypoxia MP:0005039 in MGI look correct (relate to reduced tissue levels of oxygen). However, some refer to abnormal response to a hypoxic environment. We need to review these annotations and possibly create new terms for response to hypoxic environment. 

Some examples of questionable annotations:
MGI:3531103 - in response to tissue hypoxia, soleus muscles from adult mutant mice display enhanced expression of hypoxia-inducible factors, stress proteins, and VEGF; similar molecular profiles (excluding VEGF) are noted in mutant EDL muscles
MGI:3573775 - in response to cardiac hypoxia, ventricles from E12.5 homozygotes display enhanced expression of hypoxia-inducible factors, stress proteins (heat shock proteins), and VEGF
MGI:6105935 - reduced increase in blood hemoglobin levels when housed in hypoxic chamber 
MGI:3717433 - decreased partial O2 pressure in the blood under conditions of hypoxia relative to control mice
MGI:3612981 - hypoxemia under ether anaesthesia
[hypoxia_annot.txt](https://github.com/obophenotype/mammalian-phenotype-ontology/files/5576070/hypoxia_annot.txt)

**Comment by sbello** [comment]
probably need a response to hypoxia term

**Comment by anna-anagnostop** [comment]
DEF: any anomaly in the expected response of a cell or an organism to reduced tissue levels of oxygen under physiological or pathological conditions
"'has_part' some ('process quality' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"

**Comment by sbello** [comment]
DEF: any anomaly in the expected physiological response of a cell or an organism to reduced tissue levels of oxygen under physiological or pathological conditions

**Comment by anna-anagnostop** [comment]
Added:
abnormal physiological response to hypoxia MP:0031252
SYN: abnormal physiological response to hypoxic stress
rdfs:comment This term is not to be used for behavioral responses to hypoxia.

**Comment by anna-anagnostop** [comment]
‘has part' some ('process quality' and ('inheres in' some ‘response to hypoxia’) and ('has modifier' some 'abnormal'))

**Comment by anna-anagnostop** [comment]
EQ now uses:

'has part' some 
('process quality' and ('inheres in' some GO_0001666) and ('has modifier' some abnormal))

**Comment by anna-anagnostop** [comment]
response to hypoxia GO_0001666 has been imported and used by the EQ
