### ISSUE TITLE
abnormal neurotransmitter turnover

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3349]
consider adding term for abnormal neurotransmitter turnover
see J:290567
typically measured as ratio of neurotransmitter and metabolite(s)
I've annotated this to abnormal nervous system physiology. There are a few other existing annotations for this to that term. Others have used 'abnormal neurotransmitter level' or one of the more specific abnormal level terms.

**Comment by sbello** [comment]
PMID:31431000
https://link.springer.com/chapter/10.1007/978-1-4615-9778-0_1
https://pubmed.ncbi.nlm.nih.gov/19873346/
any anomaly in process by which neurotransmitters are renewed, frequently measured as a ratio of neurotransmitter to metabolite(s) of the neurotransmitter

**Comment by sbello** [comment]
added abnormal (MP:0020970) increased (MP:0020971) and decreased (MP:0020972) terms

**Comment by anna-anagnostop** [comment]
Reopened issue to amend definition based on PMID: 30759250:
abnormal neurotransmitter turnover MP:0020970
DEF: any anomaly in the process by which neurotransmitters are renewed, frequently measured as a ratio of metabolite(s) of the neurotransmitter to the neurotransmitter itself
