### ISSUE TITLE
NPC synonym for MP:0004979 and family

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3378]
NPC is often used to abbreviate neuronal precursor cell. So it would be useful to have that as part of the synonyms for _MP:0004979 abnormal neuronal precursor cell number_ and its children and grandchildren.

**Comment by anna-anagnostop** [comment]
Added NPC as a synonym to MP:0004979 and all relevant descendant terms.
