### ISSUE TITLE
New term request: abnormal paired-pulse ratio

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3379]
>1. Preferred term label

**abnormal paired-pulse ratio**

**decreased paired-pulse ratio**

**increased paired-pulse ratio**

>2. Synonyms

**abnormal PPR**

**decreased PPR**

**increased PPR**

>3. Textual definition

**defects in the response of central synapses when activated twice in rapid succession as expressed by the ratio of the strength of the second pulse to the first pulse**

**decrease in the ratio of the strength of the second pulse to the first pulse (reduction in strength of the second pulse or increase in strength of the first pulse) in central synapses when activated twice in rapid succession** 

**increase in the ratio of the strength of the second pulse to the first pulse (increase in strength of the second pulse or decrease in strength of the first pulse) in central synapses when activated twice in rapid succession**

>4. Any additional notes to clarify the meaning or use of the term. 

**PMID:32853550 decreased PPR**

>5. Suggested parent term 

**MP:0003635 abnormal synaptic transmission**

**MP:000nnnn abnormal paired-pulse ratio**

**MP:000nnnn abnormal paired-pulse ratio**

**Comment by sbello** [comment]
abnormal - MP:0014252
increased - MP:0014254
decreased - MP:0014253
