### ISSUE TITLE
Synonym request: PPD for MP:0004807

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3380]
MP:0004807 abnormal paired-pulse inhibition
new synonym: **abnormal PPD**
new synonym: **abnormal paired-pulse depression**

PMID:32853550 paired-pulse depression PPD

Of course this term could also do with two children (decreased, increased), like MP:0002918 abnormal paired-pulse facilitation.

**Comment by sbello** [comment]
added synonyms and child terms
