### ISSUE TITLE
New term: lordokyphosis

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3384]
>1. Preferred term label 

**lordokyphosis**

>2. Synonyms 

**kypholordosis**

>3. Textual definition (the definition should be understandable even for non-specialists. 

**anteriorly convex and forward curvature of the spine, characterized by extensive flexion; a combination of kyphosis and lordosis**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**PMID:32649882 
PMID:23602569
PMID:7311623
PMID:16476774
PMID: 3214716
https://en.wiktionary.org/wiki/lordokyphosis**

>5. Suggested parent term (Please look in the hierarchy of the MP using the [MP Browser]

**MP:0004174 abnormal spine curvature**

**Comment by anna-anagnostop** [comment]
See [kyphosis-lordosis posture](https://medical-dictionary.thefreedictionary.com/kyphosis-lordosis+posture)

**Comment by anna-anagnostop** [comment]
Added new term lordokyphosis MP:0031253
Added scoliokyphosis as a new synonym for kyphoscoliosis MP:0000069 and deleted the EQ.
Also, made lordokyphosis and kyphoscoliosis children of each of the parent phenotypes.
