### ISSUE TITLE
abnormal white adipose tissue amount (MP:0001781)

### ISSUE THREAD

**Issue by slaulederkind** [mgijax/mammalian-phenotype-ontology#3386]
Consider "abnormal white adipose tissue amount" (MP:0001781), the parent of 

abnormal subcutaneous adipose tissue amount (MP:0020997)
decreased abdominal adipose tissue amount  (MP:0008853)
decreased white adipose tissue amount  (MP:0001783)
increased abdominal adipose tissue amount  (MP:0020411)
increased white adipose tissue amount (MP:0000008)

You might want to add "white" to the 2nd and fourth terms in the list.  Also consider making the 2nd and 4th terms the children of the 3rd and 5th terms, respectively.

**Comment by sbello** [comment]
Nothing in the definition specifies that the abdominal adipose tissue is only white, is this the case in all mammals?
