### ISSUE TITLE
New term: increased susceptibility to hepatic steatosis

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3389]
>1. Preferred term label 

**increased susceptibility to hepatic steatosis**

>2. Synonyms

**increased susceptibility to fatty liver development | decreased resistance to fatty liver development | decreased resistance to hepatic steatosis**

>3. Textual definition 

**more likely than normal to develop hepatic steatosis**

>4. Any additional notes to clarify the meaning or use of the term. 

**PMID:27504012 knockout exacerbates steatosis on HFD.** 

>5. Suggested parent term

**MP:0000598 abnormal liver morphology**

**Comment by anna-anagnostop** [comment]
Add new terms:

increased susceptibility to hepatic steatosis
DEF: more likely than normal to develop hepatic steatosis
SYN: increased susceptibility to fatty liver development
SYN: decreased resistance to fatty liver development
SYN: reduced resistance to fatty liver development
SYN: decreased resistance to hepatic steatosis
SYN: reduced resistance to hepatic steatosis

decreased susceptibility to alcohol-induced hepatic steatosis
DEF: less likely than normal to develop hepatic steatosis following acute or chronic alcohol administration
SYN: reduced susceptibility to alcohol-induced hepatic steatosis
SYN: reduced susceptibility to ethanol-induced hepatic steatosis
SYN: decreased susceptibility to ethanol-induced hepatic steatosis
SYN: increased resistance to alcohol-induced hepatic steatosis
SYN: increased resistance to ethanol-induced hepatic steatosis

increased susceptibility to alcohol-induced hepatic steatosis
DEF: more likely than normal to develop hepatic steatosis following acute or chronic alcohol administration
SYN: increased susceptibility to ethanol-induced hepatic steatosis
SYN: decreased resistance to alcohol-induced hepatic steatosis
SYN: reduced resistance to alcohol-induced hepatic steatosis
SYN: decreased resistance to ethanol-induced hepatic steatosis
SYN: reduced resistance to ethanol-induced hepatic steatosis

decreased susceptibility to diet-induced hepatic steatosis
DEF: less likely than normal to develop diet-induced hepatic steatosis
SYN: increased resistance to diet-induced hepatic steatosis
SYN: reduced susceptibility to diet-induced hepatic steatosis

increased susceptibility to diet-induced hepatic steatosis
DEF: more likely than normal to develop diet-induced hepatic steatosis
SYN: decreased resistance to diet-induced hepatic steatosis
SYN: reduced resistance to diet-induced hepatic steatosis


decreased susceptibility to age-related hepatic steatosis
DEF: less likely than normal to develop hepatic steatosis that is progressive with age
SYN: increased resistance to age-related hepatic steatosis
SYN: reduced susceptibility to age-related hepatic steatosis

increased susceptibility to age-related hepatic steatosis
DEF: more likely than normal to develop hepatic steatosis that is progressive with age
SYN: decreased resistance to age-related hepatic steatosis
SYN: reduced resistance to age-related hepatic steatosis
