### ISSUE TITLE
New term request: short nasal dorsum

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3395]
>1. Preferred term label
**short nasal dorsum**

>2. Synonyms
**short nose ridge | short nose**

>3. Textual definition 
**shorter than normal structure that runs from the nasal bridge to the tip of the nose.**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**PMID:32758357
google images "nasal dorsum"**

>5. Suggested parent term 
**MP:0002233 abnormal nose morphology**

**Comment by anna-anagnostop** [comment]
Definition of nasal dorsum from https://elementsofmorphology.nih.gov/anatomy-nose.shtml

Nasal Ridge:
    The midline prominence of the nose, extending from the nasal root to the tip (also called the dorsum of the nose). 


Definition of Nose, Short from https://elementsofmorphology.nih.gov/index.cgi?tid=daeb9fb85b0b970f

Objective: Distance from nasion to subnasale more than two standard deviations below the mean

Subjective: Apparently decreased length from the nasal root to the nasal tip
