### ISSUE TITLE
mp file on OBO dashboard

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3400]
For some reason the MP file on the OBO dashboard is still from 2021-01-12. We have had new releases since then. Possibly these aren't getting picked up? Do I need to do something different with the release or is it an issue on the dashboard end?

Assigning this to @matentzn and @sbello to try to figure out and then document what we need to do

**Comment by sbello** [comment]
Thanks @matentzn

**Comment by matentzn** [comment]
I think this is fixed? http://dashboard.obofoundry.org/dashboard/mp/dashboard.html

**Comment by sbello** [comment]
Yes. The file is now the one from 5/26. I meant to close this but clearly I got distracted.
