### ISSUE TITLE
improved skeletal muscle regeneration plus review of decreased/increased X regeneration terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3401]
new child of improved muscle regeneration MP:0013161 and abnormal skeletal muscle regeneration MP:0013237

need to add synonyms for enhanced/increased to this and the existing term

see J:304135 and J:238474, also existing annotations to MP:0013237

**Comment by anna-anagnostop** [comment]
Review/standardize textual definition for impaired/improved X regeneration terms (related to issues #3401 and #3474

- Rename all decreased X regeneration terms using “impaired” in primary term label (add decreased/reduced as synonyms)

- Rename all increased X regeneration terms using ‘enhanced” (add increased/improved as synonyms)

Tweak textual definition to include both injury and disease 
- Abnormal X: anomaly in the renewal, repair, and/or regrowth of [ ] following injury or disease

- Impaired: decrease in the renewal, repair, and/or regrowth of [ ] following injury or disease

- Enhanced: increase in the renewal, repair, and/or regrowth of [ ] following injury or disease

**Comment by anna-anagnostop** [comment]
Changed primary term labels for tissue specific regeneration terms (now using impaired and enhanced) and tweaked textual definitions to include both injury and disease in all instances.

Added new term:

enhanced skeletal muscle regeneration MP:0031318 (new synonyms: increased skeletal muscle regeneration, improved skeletal muscle regeneration)

Also, added new terms impaired intestine regeneration MP:0031319 and enhanced intestine regeneration MP:0031320
