### ISSUE TITLE
abnormal stress erythroposis

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3403]
abnormal stress-erythropoesis
syn: abnormal stress-induced erythropoesis
child of MP:0000245

present in J:282829, J:144586, J:89054 other existing annotations to MP:0000245

definition: any anomaly in the process by which erythroid output is increased in response to anemic stress
https://www.sciencedirect.com/science/article/abs/pii/S0301472X20303052

**Comment by anna-anagnostop** [comment]
Added:
abnormal stress erythropoiesis MP:0031276
