### ISSUE TITLE
review heme related terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3404]
J:282829 has phenotypes related to a defect in heme recycling

Currently the MP does not have any heme metabolic or homeostasis terms other than those relate to hemoglobin and porphyrin. I see annotations to hemoglobin that only mention heme levels. Heme is not synonymous with hemoglobin.

See related GO terms
heme metabolic process GO:0042168 

suggest adding:
abnormal heme metabolism
def: any anomaly in the chemical reactions and pathways involving heme, any compound of iron complexed in a porphyrin (tetrapyrrole) ring

**Comment by anna-anagnostop** [comment]
Added:
abnormal heme metabolism MP:0031275 as a child of abnormal metabolism MP:0005266 

There are a few annotations to heme defects under abnormal iron homeostasis MP:0005637 and abnormal hemoglobin MP:0001588
