### ISSUE TITLE
New term request: abnormal synaptic vesicle endocytosis

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3414]
>1. Preferred term label

**abnormal synaptic vesicle endocytosis**

>3. Textual definition

**any anomaly in the vesicle-mediated transport process in which neuronal cells form a new membrane-bounded vesicle by the invagination of a small region of the synaptic plasma membrane**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**_MP:0020848 abnormal exocytosis_ has child term _abnormal synaptic vesicle exocytosis_, so endocytosis should too. See PMID:10072535**

>5. Suggested parent term

**MP:0030951 abnormal endocytosis**

**Comment by sbello** [comment]
MP:0021013
