### ISSUE TITLE
unsatisfiable classes after last uberon release

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3436]
The build is failing because three classes are unsatisfiable:

![image](https://user-images.githubusercontent.com/7070631/126606434-a7a2667b-c403-4e06-884c-a861e561e104.png)

This is the reason:
![image](https://user-images.githubusercontent.com/7070631/126606141-1056c0ba-af18-40fa-bc61-48da3840cfd5.png)

In essence, the problem is that you cant be at the same time part of the nervous and the skeletal system; which you are  if you are a hair cell (nervous system.. sounds weird) and chochlea (skeletal system).

**Comment by matentzn** [comment]
Dont know how to fix but needs to to resume the build.

**Comment by matentzn** [comment]
Maybe related? Maybe not. https://github.com/obophenotype/uberon/issues/1905

**Comment by sbello** [comment]
Thanks Nico! I'll look into it.

**Comment by sbello** [comment]
Yes, this relates to the inference review where we objected to the inference that the cochlear hair cells were under skeletal system. Our assumption was that this was an issue with Uberon but I guess what ever fix they did made things worse?

**Comment by matentzn** [comment]
Not sure. No content work for me :D

**Comment by sbello** [comment]
Checking the eqs for these, they all follow the pattern
'has part' some 
    (absent
     and ('characteristic of' some 
        ('sensory hair cell'
         and ('part of' some cochlea)))
     and ('has modifier' some abnormal))
Guessing it is the ('part of' some cochlea) that is breaking things. 

I'm removing the and ('part of' some cochlea) 
Also changed sensory hair cell to auditory hair cell as that is a better term.

**Comment by sbello** [comment]
That fixed it. Branch merged.
