### ISSUE TITLE
Add a HP compatibility check to QC?

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3460]
@sbello If you want, I can add a test to your QC that ensures that MP is always logically compatible with HP.

**Comment by sbello** [comment]
When you get back in the new year could we test this. I don't think I'd want the build to fail but it would e good to flag these and see if there is an issue or if there is a reason that MP and HP might not be logically consistent. I'm wondering if in some cases a restriction on the HP side that is not desired on the MP side would cause issues.
