### ISSUE TITLE
change where the MP purls point

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3461]
Change the MP purls to point to the files on the MGI ftp site.

OBO file http://www.informatics.jax.org/downloads/reports/MPheno_OBO.ontology

OWL file - http://www.informatics.jax.org/downloads/reports/mp.owl

JSON file - http://www.informatics.jax.org/downloads/reports/mp.json

**Comment by matentzn** [comment]
There you go https://github.com/OBOFoundry/purl.obolibrary.org/pull/788
