### ISSUE TITLE
New child term(s) under MP:0002945 abnormal inhibitory postsynaptic currents, and other related updates

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3477]
>1. Preferred term label

**abnormal inhibitory postsynaptic current amplitude**
with children 
**decreased inhibitory postsynaptic current amplitude
increased inhibitory postsynaptic current amplitude**

Where appropriate, _MP:0002945_ should also have following children (and relevant synonyms):
**prolonged inhibitory postsynaptic current decay time
prolonged inhibitory postsynaptic current rise time
short inhibitory postsynaptic current decay time
short inhibitory postsynaptic current rise time**

>2. Synonyms

**abnormal inhibitory post-synaptic current amplitude
decreased inhibitory post-synaptic current amplitude
increased inhibitory post-synaptic current amplitude**

>3. Textual definition 

**anomaly in the size (height or maximum displacement) or shape of the evoked inhibitory postsynaptic current wave
reduction in the size (height or maximum displacement) of the evoked inhibitory postsynaptic current wave
increase in the size (height or maximum displacement) of the evoked inhibitory postsynaptic current wave**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

_MP:0002910 abnormal excitatory postsynaptic currents_ has children and grandchildren, so where appropriate, _MP:0002945 abnormal inhibitory postsynaptic currents_ should have same.

Also note that the following don't have a definition:
**MP:0011273 prolonged excitatory postsynaptic current decay time
MP:0011274 short excitatory postsynaptic current decay time**

>5. Suggested parent term 

**MP:0002945 abnormal inhibitory postsynaptic currents**

**Comment by sbello** [comment]
Also MP:0011272 has a typo in the definition "an decrease in the time required ..." guessing this should be "any"

**Comment by LaurensWilming** [comment]
> Also MP:0011272 has a typo in the definition "an decrease in the time required ..." guessing this should be "any"

Well spotted! But I think it should be "**a**" because it was probably copied from MP:0011272 "**an** increase in the time required ..."
