### ISSUE TITLE
change created_by to contributor

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3481]
Based on ticket https://github.com/pato-ontology/pato/issues/281 it appears OBO has settled on using dc:contributor instead of created by for terms. MP is currently using created by. @matentzn volunteered to modify the existing terms. @anna-anagnostop we need to modify our new term settings to use this. I think we can just change 
http: //purl.org/dc/elements/1.1/creator (no space)
to 
http: //purl.org/dc/elements/1.1/contributor
and be good but I'm double checking with Nico.

**Comment by matentzn** [comment]
Use 

```
http://purl.org/dc/terms/contributor
```

Please! the dc/elements namespace is discourced by DC itself.

Remind me of this in February - I am going on a long absence  now toll 24th January!

**Comment by sbello** [comment]
Will do. Enjoy your break!

**Comment by anna-anagnostop** [comment]
Thank you both. I will switch the creator property string in Protege using http://purl.org/dc/terms/contributor.
Nico, enjoy your time off.

**Comment by sbello** [comment]
Changed my preference setting

**Comment by anna-anagnostop** [comment]
Changed my preference setting to http://purl.org/dc/terms/contributor

**Comment by sbello** [comment]
reopening so we don't forget to clean up the existing ones
