### ISSUE TITLE
split abnormal blood-brain barrier function

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3491]
consider splitting abnormal blood-brain barrier function (MP:0005167)
add impaired/enhanced function
impaired function would be a better match to COVID symptom "Blood-brain barrier dysfunction"

**Comment by anna-anagnostop** [comment]
impaired blood-brain barrier function 
DEF: reduced ability of the group of barriers and transport systems in the brain capillary endothelium to control the entry of substances into the brain extracellular space from the blood
SYN: impaired BBB function 
SYN: increased blood-brain barrier permeability
SYN: increased BBB permeability
SYN: leaky blood-brain barrier
SYN: increased blood-brain barrier leakage
SYN: increased BBB leakage
EQ:
'has part' some 
('decreased functionality' and ('characteristic of' some ' blood brain barrier) and ('has modifier' some abnormal))

NOTE: BBB dysfunction includes (1) BBB disruption, which results in leakage of circulating substances into the CNS that can be neurotoxic; (2) transporter dysfunction, which has consequences such as inadequate nutrient supply, buildup of toxic substances in the CNS, and increased entry of compounds that are normally extruded; and (3) altered protein expression and secretions by endothelial cells and other cell types of the NVU that can result in inflammatory activation, oxidative stress, and neuronal damage. 
SOURCE: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3790938/

enhanced blood-brain barrier function 
DEF: increased ability of the group of barriers and transport systems in the brain capillary endothelium to control the entry of substances into the brain extracellular space from the blood
SYN: enhanced BBB function 
SYN: decreased blood-brain barrier permeability
SYN: decreased BBB permeability
SYN: reduced blood-brain barrier permeability
SYN: reduced BBB permeability
SYN: decreased blood-brain barrier leakage
SYN: decreased BBB leakage
SYN: reduced blood-brain barrier leakage
SYN: reduced BBB leakage

'has part' some 
('increased functionality' and ('characteristic of' some ' blood brain barrier) and ('has modifier' some abnormal))

**Comment by anna-anagnostop** [comment]
Added new child terms:
impaired blood-brain barrier function MP:0031384
enhanced blood-brain barrier function MP:0031385
