### ISSUE TITLE
decreased urine output

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3492]
Decreased urine output is currently an exact synonym for oliguria in MP but a parent to oliguria and anuria in HPO. I think the MP should change to mimic HPO since oliguia is decreased but still some urine output and anuria is absence of urination. Both would fall under decreased urine output.

**Comment by anna-anagnostop** [comment]
Added new term:

decreased urine output MP:0031358
DEF: a reduction in the volume of urine produced and excreted or the absence of urine production and excretion
Child terms include: oliguria MP:0003620 and anuria MP:0003624
