### ISSUE TITLE
red eyes

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3494]
Add a new term for "red eye"
synonym: red eyes
On the COVID spreadsheet
See also existing annotations 
http://www.informatics.jax.org/allele/allgenoviews/MGI:2448981 - incorrectly placed under abnormal eye pigmentation
http://www.informatics.jax.org/allele/allgenoviews/MGI:1856091 - under decreased eye pigmentation
http://www.informatics.jax.org/allele/allgenoviews/MGI:5578028 - under decreased eye pigmentation
plus 10 others

For reference see http://www.informatics.jax.org/vocab/hp_ontology/HP:0025337 - places this under eye vasculature not pigmentation

**Comment by anna-anagnostop** [comment]
Add new parent term:
abnormal eye vasculature morphology
DEF: any anomaly of the structure or arrangement of blood vessels supplying the eye
Child terms include: abnormal choroid vasculature morphology MP:0006237, abnormal retinal vasculature morphology MP:0002792 and abnormal conjunctival vasculature morphology MP:0006192 

Add new child term:
red eye
DEF: a condition where the white part of the eye (sclera) appears reddened or bloodshot, ranging from a few enlarged blood vessels appearing as wiggly lines over the sclera to a bright red color completely covering to sclera
SYN: red eyes

Child terms of red eye include: conjunctival hyperemia

**Comment by sbello** [comment]
need a curator comment that this is for vascular related redness not the red eyes seen in albinism
