### ISSUE TITLE
aortic bulb aneurysm

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3496]
Add new term aortic bulb aneurysm
synonym aortic root aneurysm
see http://www.informatics.jax.org/vocab/hp_ontology/HP:0002616
annotations in MGI - J:204960

**Comment by anna-anagnostop** [comment]
Added new term:
aortic bulb aneurysm MP:0031344 (a child of abnormal aorta bulb morphology MP:0011572 and ascending aorta aneurysm MP:0010661)
DEF: a protruding sac formed by the dilation of the wall of the aortic bulb resulting from a weakening of the vessel wall
SYN: aortic root aneurysm

QUESTION: should aortic bulb aneurysm be a direct child of dilated aorta bulb MP:0011575? Also, should MP:0011575 be a direct child of ascending aorta dilation MP:0010470? Looking at the terms for aorta dilation and aortic aneurysm it looks like these should remain as siblings.

**Comment by sbello** [comment]
Yes, it makes sense to put the aneurysm under dilation as it is localized dilation
