### ISSUE TITLE
bone fibrous dysplasia

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3497]
add term for fibrous bone dysplasia
see http://www.informatics.jax.org/vocab/hp_ontology/HP:0010734
see J:160299, J:216100, J:240241 for existing annotations, these are scattered under different MP terms currently

**Comment by anna-anagnostop** [comment]
Add new terms:

1. fibrous bone dysplasia (a child of abnormal bone structure MP:0003795 or abnormal bone remodeling MP:0002998)
DEF: a typically benign bone disorder where normal bone and marrow is replaced with scar-like (fibrous) connective tissue, resulting in formation of bone that is weak and prone to expansion; may affect one solitary bone (monostotic), multiple bones (polyostotic) or the entire skeleton (panostotic)
SYNONYMS: fibrous dysplasia of bone
SOURCE: https://en.wikipedia.org/wiki/Fibrous_dysplasia_of_bone, https://rarediseases.org/rare-diseases/fibrous-dysplasia/

CHECK PLACEMENT: 
HPO places Fibrous dysplasia of the bones [HP:0010734](http://www.informatics.jax.org/vocab/hp_ontology/HP:0010734) under Abnormal bone structure HP:0003330 
According to the DO, fibrous dysplasia [DOID:0080031](http://www.informatics.jax.org/disease/DOID:0080031) is a bone remodeling disease 

1a. monostotic fibrous dysplasia
DEF: a form of fibrous dysplasia affecting one solitary bone  


1b. polyostotic fibrous dysplasia (update KidsFirst Mapping)
DEF: a form of fibrous dysplasia affecting multiple bones throughout the body 
Annotations from J:240241 (polyostotic)

**Comment by sbello** [comment]
Suggest trimming definition to:
normal bone and marrow is replaced with scar-like (fibrous) connective tissue, resulting in formation of bone that is weak and prone to expansion; may affect one solitary bone (monostotic), multiple bones (polyostotic) or the entire skeleton (panostotic)

If we add the children I think you could drop " may affect one solitary bone (monostotic), multiple bones (polyostotic) or the entire skeleton (panostotic)"

**Comment by anna-anagnostop** [comment]
Added new terms:
bone fibrous dysplasia MP:0031348
monostotic fibrous dysplasia MP:0031349
polyostotic fibrous dysplasia MP:0031350
