### ISSUE TITLE
meningocele

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3500]
Correct definition of meningocele (MP:0012259)
current definition: "a protrusion of meninges through dehiscences in the base of the skull or gaps between the vertebrae, resulting in a cyst filled with cerebrospinal fluid; nervous tissue remains unaffected"

suggested definition ""a protrusion of meninges through one or more defect in the the skull or spinal column, resulting in a cyst filled with cerebrospinal fluid; nervous tissue remains unaffected"
source: Taber's edition 19 ISBN 0-8036-0655-9

Note HPO has a term with the same name Meningocele (HP:0002435) that only mentions "vertebral column" in the definition but has skull defect related children.

**Comment by sbello** [comment]
See HPO also ticket https://github.com/obophenotype/human-phenotype-ontology/issues/7292

**Comment by anna-anagnostop** [comment]
Definition of meningocele MP:0012259 has been corrected.
