### ISSUE TITLE
children of increased mast cell number

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3510]
Consider adding location specific child terms
Many existing annotations mention skin (HPO term Cutaneous mastocytosis, HP:0200151)
also annotations for spleen, lymph nodes, intestines, liver (Hepatic mastocytosis HP:0031824) 

add synonym - mastocytosis

**Comment by anna-anagnostop** [comment]
Added "mastocytosis" as an exact synonym of increased mast cell number MP:0000324.

Added new term cutaneous mastocytosis MP:0031395
DEF: presence of excess mast cell numbers in any portion of the skin
SYN: increased mast cell number in the skin
SYN: increased cutaneous mast cell number
SYN: increased skin mast cell number
Comment: Cutaneous mastocytosis is limited to the skin whereas systemic mastocytosis affects extracutaneous tissues (such as spleen, liver, bone marrow, and lymph nodes) in addition to skin.
https://www.uptodate.com/contents/mastocytosis-cutaneous-and-systemic-in-children-epidemiology-clinical-manifestations-evaluation-and-diagnosis, https://www.mdpi.com/2077-0383/10/7/1474/htm
