### ISSUE TITLE
epispadia

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3512]
The MP definition of epispadia (MP:0003598) includes both males and females the HP definition (HP:0000039) covers only males.

The MP definition agrees with those at: 
https://www.hopkinsmedicine.org/health/conditions-and-diseases/epispadias 
https://www.urologyhealth.org/urology-a-z/e/epispadias
https://my.clevelandclinic.org/health/diseases/21551-epispadias
https://www.chop.edu/conditions-diseases/epispadias

The MP term is currently incorrectly placed under abnormal penis morphology (MP:0005187) given the term definition. This parent should be removed.

**Comment by anna-anagnostop** [comment]
Parent term abnormal penis morphology (MP:0005187) has been removed.
