### ISSUE TITLE
Wrong datatype for PMID number in mp.owl for hasDbXref in MP_0021064 (?)

### ISSUE THREAD

**Issue by motey** [mgijax/mammalian-phenotype-ontology#3530]
Source file: https://github.com/mgijax/mammalian-phenotype-ontology/releases/download/v2022-02-24/mp.owl

Line: 911122

is datatype `short` (https://www.w3.org/TR/xmlschema-2/#short)

`<oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#short">PMID:16416090</oboInOwl:hasDbXref>`

but should be `string` (https://www.w3.org/TR/xmlschema-2/#string)

`<oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:16416090</oboInOwl:hasDbXref>`

this breaks my neo4j rdf parser (https://neo4j.com/labs/neosemantics/)

`Error: java.lang.NumberFormatException: For input string: "PMID:16416090"` 

Sorry, i dont have too much understanding with owl parsing. i am just starting. So is this a bug in the source data or am i stupid ? :) 

Thanks for any hints :heart:

**Comment by anna-anagnostop** [comment]
Thank you for pointing this out. Datatype for PMID number has been changed to string in MP_0021064.
