### ISSUE TITLE
Abnormal bicarbonate homeostasis

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3534]
From Melissa:
We have “decreased circulating bicarbonate level” and “increased urine bicarbonate level” so…
Abnormal bicarbonate homeostasis? Child of 1765 maybe?
Or would that be superfluous? I’ve got a mutant defective in a membrane solute carrier of the bicarbonate transporter family so I’m wondering.

We should check the existing annotations to see if a grouping term would be useful

**Comment by anna-anagnostop** [comment]
Add new term:
abnormal bicarbonate homeostasis (a child of abnormal ion homeostasis MP:0001765)
DEF: anomaly in the processes involved in the maintenance of an internal equilibrium of bicarbonate within the body or between a cell and its external environment; bicarbonate is a polyatomic anion with the chemical formula HCO3- that serves a crucial role in the physiological pH buffering system
SYN: abnormal hydrogencarbonate homeostasis
SYN: abnormal HCO3- homeostasis
SOURCE: CHEBI:17544
Comment: IUPAC (International Union of Pure and Applied Chemistry)-recommended nomenclature is hydrogencarbonate with the chemical formula CHO3.

abnormal bicarbonate level (child of new term abnormal bicarbonate homeostasis)
DEF: any anomaly in the concentration of bicarbonate in the body
SYN: abnormal hydrogencarbonate level
SYN: abnormal HCO3- level

Child terms include:
abnormal urine bicarbonate level terms

**Comment by anna-anagnostop** [comment]
Added new terms:
abnormal bicarbonate homeostasis MP:0031393
abnormal bicarbonate level MP:0031394
