### ISSUE TITLE
Metadata standardisation: ORCIDs

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3537]
Just one missing piece: Who is "RGD:cp"? Annotated to three terms. If you provide an ORCID I can make a quick fix.

**Comment by sbello** [comment]
I'll check with RGD to see if I can find that out

**Comment by sbello** [comment]
ORCID is [0000-0002-7698-0055](https://orcid.org/0000-0002-7698-0055) full name Cody Plasterer
