### ISSUE TITLE
New synonym request for MP:0001402 hypoactivity

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3550]
New synonym request for MP:0001402 hypoactivity:
**_reduced physical activity_**

**Comment by sbello** [comment]
Currently hypoactivity is defined as reduced locomotor activity so reduced physical activity is broader
Hyperactivity on the other hand is any type of movement
Suggest hypoactivity changes the label to decreased locomotor activity
create a new term for hypoactivity that covers any type of movement
decreased locomotor activity - child of abnormal locomotor behavior
move hyperactivity out to abnormal voluntary movement
create new term for increased locomotor activity, child of hyperactivity and abnormal locomotor behavior
hypo/hyperactivity would also have vertical activity children

**Comment by sbello** [comment]
dystonia moves to under involuntary movement
behavioral arrest moves to under abnormal locomotor behavior
bradykinesia move to be a child of the new hypoactivity term
lethargy child of new hypoactivity term and decreased alertness
positive geotaxis - move under abnormal locomotor behavior
retropulsion - move under abnormal locomotor behavior

**Comment by anna-anagnostop** [comment]
Changed term label for existing hypoactivity term to decreased locomotor activity

Added new term hypoactivity MP:0031392

Added new term increased locomotor activity MP:0031391
