### ISSUE TITLE
Update all reviewed patterns

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3555]
Using the update-replace workflow, replace all fully reviewed pattern EQs in MP.

**Comment by rays22** [comment]
I am blocked at making a new definitions.owl:

> ...
make: *** [Makefile:474: ../patterns/data/default/cystInLocation.ofn] Error 1

**Comment by matentzn** [comment]
Need more context to understand what is wrong. What is the whole error message?

**Comment by rays22** [comment]
>  sh run.sh make ../patterns/definitions.owl IMP=false
mp.Makefile:24: warning: overriding recipe for target 'test'
Makefile:73: warning: ignoring old recipe for target 'test'
mp.Makefile:28: warning: overriding recipe for target 'mp.owl'
Makefile:538: warning: ignoring old recipe for target 'mp.owl'
mp.Makefile:33: warning: overriding recipe for target 'mp.obo'
Makefile:542: warning: ignoring old recipe for target 'mp.obo'
if [ true  = true ] && [ "abnormalMorphologyOfAnatomicalEntity abnormallyDilatedAnatomicalEntity abnormalBiologicalProcessInLocation abscessInLocation blisteredAnatomicalEntity abnormalWeightOfAnatomicalEntity abnormalFunctionalityOfAnatomicalEntity cystInLocation abnormallyDecreasedSizeOfAnatomicalEntity abnormallyIncreasedWidthOfAnatomicalEntity abnormallyDecreasedLengthOfAnatomicalEntity abnormallyIncreasedSizeOfAnatomicalEntity abnormallyIncreasedVolumeOfAnatomicalEntity atrophiedAnatomicalEntity" ]; then dosdp-tools generate --catalog=catalog-v001.xml --infile=../patterns/data/default/ --template=../patterns/dosdp-patterns --batch-patterns="abnormalMorphologyOfAnatomicalEntity abnormallyDilatedAnatomicalEntity abnormalBiologicalProcessInLocation abscessInLocation blisteredAnatomicalEntity abnormalWeightOfAnatomicalEntity abnormalFunctionalityOfAnatomicalEntity cystInLocation abnormallyDecreasedSizeOfAnatomicalEntity abnormallyIncreasedWidthOfAnatomicalEntity abnormallyDecreasedLengthOfAnatomicalEntity abnormallyIncreasedSizeOfAnatomicalEntity abnormallyIncreasedVolumeOfAnatomicalEntity atrophiedAnatomicalEntity" --ontology=mp-edit.owl --obo-prefixes=true --restrict-axioms-to=logical --outfile=../patterns/data/default; fi
make: *** [Makefile:474: ../patterns/data/default/cystInLocation.ofn] Error 1
