### ISSUE TITLE
MP using wrong occurs in

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3565]
- [ ] Need to replace with BFO:66
- [ ] Add qc check to prevent from happening again

**Comment by matentzn** [comment]
There are 506 wrong usages:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/7070631/163410951-cf973b79-ad6a-4fc5-9cc9-3e39d9a1b881.png">

**Comment by sbello** [comment]
Is this something you can fix with a script? Or do we need to do it manually?

**Comment by matentzn** [comment]
I will do it, 2 seconds.
