### ISSUE TITLE
New MPD terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3568]
email from Molly 
Requested term: abnormal trimethylamine N-oxide level
Proposed parent: MP:0009642 abnormal blood homeostasis
Proposed def: abnormal amount of this metabolite which is derived from gut bacteria; high levels are associated with heart disease hardening of arteries, diabetes, and colon cancer

Requested term: abnormal betaine level
Proposed parent: MP:0009642 abnormal blood homeostasis
Proposed def: abnormal amount of this modified amino acid consisting a glycine with three methyl groups serving as methyl donor for various metabolic pathways

Requested term: abnormal phosphocholine level
Proposed parent: MP:0009642 abnormal blood homeostasis
Proposed def: abnormal amount of this intermediate in the synthesis of phosphatidylcholine in tissues

Requested term: abnormal glycerophosphocholine level
Proposed parent: MP:0009642 abnormal blood homeostasis
Proposed def: abnormal amount of this choline derivative and one of two major forms of choline storage (the other is phosphocholine) in the cytosol

**Comment by anna-anagnostop** [comment]
Looking at our annotations:

trimethylamine N-oxide level (TMAO) 
NOTE: Existing MP annotation from [J:174999](http://www.informatics.jax.org/reference/J:174999) (decreased trimethylamine-N-oxide (TMAO) urinary excretion)
Usefull reference: PMID: [30275434](https://www.ncbi.nlm.nih.gov/pubmed/30275434)
SOURCE: [CHEBI:15724](http://purl.obolibrary.org/obo/CHEBI_15724), [Wikipedia:Trimethylamine_oxide](http://en.wikipedia.org/wiki/Trimethylamine_oxide)

betaine
Existing MP annotations from [J:177569](http://www.informatics.jax.org/reference/J:177569) (reported in tissues, esp liver, under [abnormal amino acid level](http://www.informatics.jax.org/vocab/mp_ontology/MP:0005332)), [J:286033](http://www.informatics.jax.org/reference/J:286033) (reported in brain and plasma)
SOURCE: [CHEBI:17750](http://purl.obolibrary.org/obo/CHEBI_17750), [Wikipedia:Trimethylglycine](http://en.wikipedia.org/wiki/Trimethylglycine)

phosphocholine
Existing MP annotations from [J:267987](http://www.informatics.jax.org/reference/J:267987) (reported in various tissues under [decreased choline level](http://www.informatics.jax.org/vocab/mp_ontology/MP:0030753), [J:267002](http://www.informatics.jax.org/reference/J:267002) (reported in skin, under [abnormal lipid level](http://www.informatics.jax.org/vocab/mp_ontology/MP:0001547) and [abnormal skin morphology](http://www.informatics.jax.org/vocab/mp_ontology/MP:0002060)), [J:111561](http://www.informatics.jax.org/reference/J:111561) (reported in alveolar macrophages)
SOURCE: [CHEBI:18132](http://purl.obolibrary.org/obo/CHEBI_18132) 

glycerophosphocholine 
Existing MP annotation from [J:267002](http://www.informatics.jax.org/reference/J:267002) (reported in skin, under [abnormal lipid level](http://www.informatics.jax.org/vocab/mp_ontology/MP:0001547) and [abnormal skin morphology](http://www.informatics.jax.org/vocab/mp_ontology/MP:0002060))
SOURCE: [CHEBI:36313](http://purl.obolibrary.org/obo/CHEBI_36313)

**Comment by sbello** [comment]
Thanks Anna. I'll add these today.

**Comment by sbello** [comment]
abnormal trimethylamine N-oxide level child of abnormal homeostasis, also added increased and decreased children MP:0021122-MP:0021124

**Comment by sbello** [comment]
emailed Molly to determine if we should add amino acid betaine or the more specific term glycine betaine

**Comment by sbello** [comment]
added the general amino-acid betaine term
all requested terms plus increased and decreased children added
