### ISSUE TITLE
How to download specific (e.g. older) version of MP.owl?

### ISSUE THREAD

**Issue by moldach** [mgijax/mammalian-phenotype-ontology#3578]
The link that I've found to download the MP ontology in .owl format from EBI (https://www.ebi.ac.uk/ols/ontologies/mp)
only provides the _most-recent_ version of the ontology

I need a way to programatically chose which version of the ontology I download; however, I'm not sure where to find this...

The EBI website provides a **non-functioning** link: **Version IRI**: http://purl.obolibrary.org/obo/mp/releases/2022-04-08
which leads to a **400: Invalid request** error.

Could you please let me know where I can get previous releases from?

**Comment by sbello** [comment]
We have releases on GitHub. I think the link format
https://github.com/mgijax/mammalian-phenotype-ontology/releases/download/v2022-04-06/mp.owl
where you modify the vYear-month-day to the release you want should work.

**Comment by matentzn** [comment]
When this is merged: 
https://github.com/OBOFoundry/purl.obolibrary.org/pull/849

You can obtain every MP artefact from its version PURLs.. Surprising this was not noticed before!

http://purl.obolibrary.org/obo/mp/releases/2022-04-08/mp.obo

**Comment by sbello** [comment]
Thanks @matentzn 
The pull request Nico created has been merged so the purls should work now.

**Comment by sbello** [comment]
reopening as the links aren't working yet, will double check tomorrow

**Comment by matentzn** [comment]
Works for me:

http://purl.obolibrary.org/obo/mp/releases/2022-04-21/mp.obo

**Comment by sbello** [comment]
Odd the 2022-04-08 link above did not work but the 2022-04-21 link did 
And now checking the releases I see why, we have an 2022-04-06 release but not an 08 release.
Reclosing.
