### ISSUE TITLE
Check EQs for early and delayed sexual maturation

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#3591]
delayed sexual maturation MP:0001938
EQ currently uses:
'has part' some 
(delayed and ('characteristic of' some 'development of secondary sexual characteristics') and ('has modifier' some abnormal))

early sexual maturation MP:0003378
EQ currently uses:
'has part' some 
(premature and ('characteristic of' some 'animal organ development') and ('has modifier' some abnormal) and (has_central_participant some 'reproductive organ'))

**Comment by sbello** [comment]
Change both to use developmental process involved in reproduction GO:0003006
