### ISSUE TITLE
Typos in MP:0012207 decreased neuronal stem cell self-renewal

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3614]
MP:0012207 decreased neuronal stem cell self-renewal definition:

_**an** decreased rate in the process by which stem cells divide and proliferate to make more stem cells, perpetuating **an** decrease in the stem cell pool_

should be 

_**a** decreased rate in the process by which stem cells divide and proliferate to make more stem cells, perpetuating **a** decrease in the stem cell pool_

You may want to search for "decrease" in other definitions (or "an decrease") to check if this occurs elsewhere too.

**Comment by sbello** [comment]
done, fixed a couple other occurrences of this
