### ISSUE TITLE
calcified intervertebral disk

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3631]
definition is "process in which the cartilaginous and gelatinous structure found between vertebrae becomes hardened due to deposits of calcium salts" but definition and placement indicate that this is the end product of this process not the process

consider revising the definition to make it clear that this is the morphological out come not the process

**Comment by anna-anagnostop** [comment]
Changed definition to "pathologic deposition of calcium salts in one or more intervertebral disks" to be consistent with other calcified MP terms.
New synonyms added: calcified intervertebral disks | calcified intervertebral discs
