### ISSUE TITLE
Unsats in latest release

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3642]
# Unsatisfiable classes in current MP

We need to figure out what exactly is wrong, but my guess is incompatible imports.

## [absent barrels in primary somatosensory cortex](http://purl.obolibrary.org/obo/MP_0000862) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [absent barrels in primary somatosensory cortex](http://purl.obolibrary.org/obo/MP_0000862) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some 
([absent](http://purl.obolibrary.org/obo/PATO_0000462) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some 
([barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [primary somatosensory cortex](http://purl.obolibrary.org/obo/UBERON_0008933)))) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460)))
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014)
      - [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) SubClassOf [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616)
        - [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) EquivalentTo [multi-tissue structure](http://purl.obolibrary.org/obo/UBERON_0000481) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/UBERON_0000955))
          - [brain](http://purl.obolibrary.org/obo/UBERON_0000955) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942)
      - [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) EquivalentTo [sensory system](http://purl.obolibrary.org/obo/UBERON_0001032) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012))
        - [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010)
    -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) DisjointWith [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)

## [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014)
    - [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) SubClassOf [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616)
      - [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) EquivalentTo [multi-tissue structure](http://purl.obolibrary.org/obo/UBERON_0000481) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/UBERON_0000955))
        - [brain](http://purl.obolibrary.org/obo/UBERON_0000955) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)
  - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942)
    -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
    - [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) EquivalentTo [sensory system](http://purl.obolibrary.org/obo/UBERON_0001032) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012))
      - [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) DisjointWith [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)

## [abnormal barrel cortex morphology](http://purl.obolibrary.org/obo/MP_0003989) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [abnormal barrel cortex morphology](http://purl.obolibrary.org/obo/MP_0003989) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some
([morphology](http://purl.obolibrary.org/obo/PATO_0000051) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415)) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460)))
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014)
      - [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) SubClassOf [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616)
        - [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) EquivalentTo [multi-tissue structure](http://purl.obolibrary.org/obo/UBERON_0000481) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/UBERON_0000955))
          - [brain](http://purl.obolibrary.org/obo/UBERON_0000955) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942)
      -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
      - [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) EquivalentTo [sensory system](http://purl.obolibrary.org/obo/UBERON_0001032) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012))
        - [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) DisjointWith [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)

## [disorganized barrel cortex](http://purl.obolibrary.org/obo/MP_0000861) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [disorganized barrel cortex](http://purl.obolibrary.org/obo/MP_0000861) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some
([disorganized](http://purl.obolibrary.org/obo/PATO_0000937) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415)) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460)))
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014)
      - [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) SubClassOf [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616)
        - [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) EquivalentTo [multi-tissue structure](http://purl.obolibrary.org/obo/UBERON_0000481) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/UBERON_0000955))
          - [brain](http://purl.obolibrary.org/obo/UBERON_0000955) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)
    - [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942)
      - [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012)
        - [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010)
      -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) DisjointWith [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)

# Axiom Impact
## Axioms used 4 times
- [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) EquivalentTo [multi-tissue structure](http://purl.obolibrary.org/obo/UBERON_0000481) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/UBERON_0000955)) [pato_import.owl,uberon_import.owl]
- [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) [pato_import.owl,uberon_import.owl]
- [brain](http://purl.obolibrary.org/obo/UBERON_0000955) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017) [pato_import.owl,uberon_import.owl]
- [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) [uberon_import.owl]
- [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) [uberon_import.owl]
- [functional part of brain](http://purl.obolibrary.org/obo/UBERON_0035014) SubClassOf [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616) [uberon_import.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [peripheral nervous system](http://purl.obolibrary.org/obo/UBERON_0000010) DisjointWith [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017) [uberon_import.owl]
-  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050) [pr_import.owl,ro_import.owl,pato_import.owl,go_import.owl,uberon_import.owl]

## Axioms used 3 times
- [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) EquivalentTo [sensory system](http://purl.obolibrary.org/obo/UBERON_0001032) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012)) [pato_import.owl]

## Axioms used 1 times
- [disorganized barrel cortex](http://purl.obolibrary.org/obo/MP_0000861) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some
([disorganized](http://purl.obolibrary.org/obo/PATO_0000937) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415)) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460))) [mp.owl]
- [absent barrels in primary somatosensory cortex](http://purl.obolibrary.org/obo/MP_0000862) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some
([absent](http://purl.obolibrary.org/obo/PATO_0000462) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some
([barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [primary somatosensory cortex](http://purl.obolibrary.org/obo/UBERON_0008933)))) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460))) [mp.owl]
- [abnormal barrel cortex morphology](http://purl.obolibrary.org/obo/MP_0003989) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some
([morphology](http://purl.obolibrary.org/obo/PATO_0000051) and ([characteristic of](http://purl.obolibrary.org/obo/RO_0000052) some [barrel cortex](http://purl.obolibrary.org/obo/UBERON_0010415)) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460))) [mp.owl]
- [somatic sensory system](http://purl.obolibrary.org/obo/UBERON_0003942) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [somatic nervous system](http://purl.obolibrary.org/obo/UBERON_0000012) [pato_import.owl]

# Ontologies used:
- uberon_import.owl (http://purl.obolibrary.org/obo/mp/imports/uberon_import.owl)
- go_import.owl (http://purl.obolibrary.org/obo/mp/imports/go_import.owl)
- pr_import.owl (http://purl.obolibrary.org/obo/mp/imports/pr_import.owl)
- pato_import.owl (http://purl.obolibrary.org/obo/mp/imports/pato_import.owl)
- ro_import.owl (http://purl.obolibrary.org/obo/mp/imports/ro_import.owl)
- mp.owl (http://purl.obolibrary.org/obo/mp.owl)

**Comment by matentzn** [comment]
@shawntanzk pointed me to https://github.com/obophenotype/uberon/pull/2534#pullrequestreview-1027446876

I will try to rerun a PATO release to see this goes away.

**Comment by shawntanzk** [comment]
It probably won't - I did not change that axiom previously, instead I changed the part_of system axiom. But perhaps we should look at changing that axiom. Let me look into it a bit more
