### ISSUE TITLE
cleft palate terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3646]
consider expanding cleft palate children similar to what is in HPO (children of HP:0000175)

MGI has annotations for 
bilateral cleft palate (see HP:0100337)
median cleft palate (cleft at the midline, HP:0009099)
unilateral cleft (usually annotated as bilateral or unilateral, which would fall under non-midline cleft HP:0100338)

**Comment by sbello** [comment]
J:323190
abnormal palatal mesenchymal cell proliferation
abnormal palatal mesenchymal cell differentiation
increased DNA damage - currently annotated to cell physiology, no exposure to DNA damaging agent, not increased cell death

**Comment by sbello** [comment]
J:317609
abnormal palatal shelf size

**Comment by sbello** [comment]
related to this we need some tongue development terms, see J:296645 failure of tongue to descend in the oral cavity during development, currently annotated to tongue morphology

**Comment by sbello** [comment]
should add terms for abnormal/increased/decreased palatal shelf size 
see J:310908

**Comment by sbello** [comment]
added 
abnormal palatopharyngeus muscle morphology - MP:0021202
abnormal palatine aponeurosis morphology - MP:0021203
abnormal superior pharyngeal constrictor muscle morphology - MP:0021204

**Comment by anna-anagnostop** [comment]
We will need to import PATO terms split medially [PATO:0002169](http://purl.obolibrary.org/obo/PATO_0002169), split laterally [PATO:0002170](http://purl.obolibrary.org/obo/PATO_0002170), and split bilaterally [PATO:0002171](http://purl.obolibrary.org/obo/PATO_0002171) to create the EQs for median, unilateral and bilateral cleft palate terms. 

See also  midline facial cleft - synonym and EQ #3663 and  cleft upper lip - add new child terms #3664

**Comment by sbello** [comment]
@anna-anagnostop do you want to talk about this on Monday? I think this should be easy enough to do.

**Comment by anna-anagnostop** [comment]
Yes, let's do that!

**Comment by sbello** [comment]
run into several papers that have the phenotype "premature ossification of palatal shelf bone"
currently annotating to premature bone ossification
need to clarify are palatal shelf bones all of a single type of bone (endochondrial vs intramembranous) 
If we add a term for "premature ossification of palatal shelf bone" where would this go? The  premature bone ossification lives under skeleton physiology but all the palatal terms are under morphology/development. It seems like this should be under development but we don't put terms under both morph and physiology.
Looking at this https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/Book%3A_General_Biology_(Boundless)/38%3A_The_Musculoskeletal_System/38.07%3A_Bone_-_Bone_Development and given all the mesenchymal annotations I've been finding I think these would be intramembranous.

**Comment by sbello** [comment]
add abnormal palatal shelf morphology

**Comment by sbello** [comment]
PMID:29184513 has useful info and references for palatal development

**Comment by sbello** [comment]
J:278485 - add a term for abnormal spontaneous fetal mouth movement child of abnormal stationary movement (MP:0001388)
any anomaly in the spontaneous neuromuscular movements of the mandible and tongue prior to birth

comment: these movements play a role in proper development of the palate

**Comment by sbello** [comment]
Subdivide cleft palate

bilateral cleft palate (see HP:0100337)
median cleft palate (cleft at the midline, HP:0009099)
unilateral cleft (usually annotated as bilateral or unilateral, which would fall under non-midline cleft HP:0100338; unilateral primary cleft, J:217408)
complete secondary palate cleft (J:213412, J:90453)
partial secondary palate cleft (J:122604, anterior and mid cleft; J:160190, partial anterior fusion; J:50951, anteroposterior cleft; probably more)
anterior cleft palate - J:277246 "failure of palatal fusion, specifically at the anterior portion between the primary and the secondary palate, with failed disintegration of the medial-edge epithelium"

**Comment by sbello** [comment]
Adding cleft palate subtypes:

median cleft palate - MP:0021208
non-midline cleft palate - MP:0021209
bilateral cleft palate - MP:0021210
unilateral cleft - MP:0021211
complete cleft palate - MP:0021213
anterior cleft palate - MP:0021214
abnormal primary and secondary palatal fusion - MP:0021212

useful reference PMID: 3074914

**Comment by anna-anagnostop** [comment]
Per PMID:27761803, The palatal shelves continue to grow until contact is made in the midline at E15, followed by epithelium degeneration and extrusion and finally fusion of the underlying mesenchyme to complete formation of the secondary palate by E15.5.(Bush and Jiang [2012](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR6); Hill et al. [2015](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR20); Kim et al. [2015](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR23); Parada and Chai [2012](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR37); Smith et al. [2012](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR43)) **The mesenchymal cells in the anterior portion undergo intramembranous ossification to form the hard (bony) palate,(Bush and Jiang [2012](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR6); Levi et al. [2011](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR27)) while those in the posterior portion differentiate into skeletal muscle to form the soft palate.(Bush and Jiang [2012](https://www-ncbi-nlm-nih-gov.ezproxy.jax.org/pmc/articles/PMC5362573/#CR6))**

**Comment by sbello** [comment]
closing this as we've moved on to other diseases for KidsFirst
