### ISSUE TITLE
Finish automated release

### ISSUE THREAD

**Issue by matentzn** [mgijax/mammalian-phenotype-ontology#3655]
For @sbello:

- [x] Go [here to the untagged release draft](https://github.com/mgijax/mammalian-phenotype-ontology/releases/tag/untagged-d9e8a6a56a3907bc558b)
- [x] Download mp.obo and make sure it looks ok., i.e. having the latest changes (I think it does)
- [x] Click on the pen symbol top right corner
- [x] Change title and the Description to whatever you want
- [x] Click "publish release"

You can use the same instructions in the future for finalising releases.

**Comment by sbello** [comment]
This worked. Does this mean the build is now fully in GitHub actions?

**Comment by matentzn** [comment]
It gives me 98.2% confidence which is pretty high. For now.

**Comment by matentzn** [comment]
(Yes it should work)

**Comment by sbello** [comment]
2 releases done using the new actions pipeline, so I am closing this
