### ISSUE TITLE
decreased neural crest cell apoptosis

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3670]
child of MP:0009844 
currently we only have increased and abnormal but =not decreased
J:308882 has decreased cranial neural crest cell apoptosis

**Comment by anna-anagnostop** [comment]
Added new term:

decreased neural crest cell apoptosis MP:0031452

Also added:

decreased cardiac neural crest cell apoptosis MP:0031453
decreased cranial neural crest cell apoptosis MP:0031454
decreased trunk neural crest cell apoptosis MP:0031455
decreased vagal neural crest cell apoptosis MP:0031456
