### ISSUE TITLE
new synonyms for MP:0003928 and MP:0003929

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3691]
>2. Synonyms 

**MP:0003928 increased heart rate variability**
increased heart rate variation
increased HRV

**MP:0003929 decreased heart rate variability**
decreased heart rate variation
reduced heart rate variation
decreased HRV
reduced HRV

**Comment by anna-anagnostop** [comment]
New suggested synonyms for MP:0003928 and MP:0003929 have been added.
