### ISSUE TITLE
new term: abdominal effusion

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3694]
>1. Preferred term label 

**abdominal effusion**

>2. Synonyms 

**abdominal fluid accumulation**

>3. Textual definition

**fluid accumulation in the abdomen**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**PMID:14609031 p.207**

>5. Suggested parent term 

**MP:0000676	abnormal body water content**

**Comment by sbello** [comment]
We need to modify this definition to make clear what the distinction between edema and effusion is. Looking in the HPO I see "accumulation of fluid" used in definitions for both.
Looking online for definitions of effusion I find "an escape of fluid into a body cavity."
From NCI (https://www.cancer.gov/publications/dictionaries/cancer-terms/def/effusion) "An abnormal collection of fluid in hollow spaces or between tissues of the body. For example, a pleural effusion is a collection of fluid between the two layers of membrane covering the lungs."

We have a term for edema in the MP under abnormal fluid regulation it may be helpful to add a term for effusion as well

**Comment by sbello** [comment]
looking into this further abdominal effusion = ascites
I have added a new grouping term for effusion (MP:0021205) and added new synonyms to ascites
