### ISSUE TITLE
palatal taste bud terms

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#3715]
Consider adding:

abnormal palatal taste bud morphology (a child of abnormal soft palate morphology MP:0003154)
DEF: any structural anomaly of the taste bud, a specialized receptor organ consisting of a group of clustered sensory cells, located on the soft palate, in the roof of the mouth; palatal taste buds lack supporting papilla structures and are directly embedded in the epithelium of the soft palate
SOURCE: PMID:25299669
SOURCE: UBERON:0034670

absent palatal taste bud
DEF: absence of the palatal taste bud that normally develops in the epithelium of the soft palate without associated papilla structures
SYN: absent palatal taste buds
Annotations from J:112945

**Comment by anna-anagnostop** [comment]
Added new terms:

abnormal palatal taste bud morphology MP:0031466
absent palatal taste bud MP:0031467


Also, currently, the EQ for abnormal soft palate morphology MP:0003154 uses 'quality' and 'characteristic of'. Changed EQ to use:
'has part' some 
    (**morphology**
     and ('**characteristic of part of**' some 'soft palate')
     and ('has modifier' some abnormal))

**Need to review abnormal taste bud morphology MP:0001002** def refers specifically to the tongue but this appears to be the same as its child term abnormal gustatory papillae taste bud morphology MP:0006260

**Comment by sbello** [comment]
To Do:

- [ ] obsolete existing abnormal taste bud morphology
- [ ] create a new abnormal taste bud morphology that is NOT specific to tongue
- [ ] move existing term annotations to MP:0006260 and update synonyms
- [ ] place palate taste bud term under new abnormal taste bud morphology

**Comment by anna-anagnostop** [comment]
- Obsoleted existing abnormal taste bud morphology MP:0001002 

- Created new term for abnormal taste bud morphology that is NOT specific to tongue MP:0031468.

- Moved existing term annotations to abnormal gustatory papillae taste bud morphology MP:0006260 and updated synonyms

- Placed palate taste bud terms MP:0031466 and MP:0031467 under new abnormal taste bud morphology MP:0031468

- Placed abnormal gustatory papillae taste bud morphology MP:0006260 under abnormal gustatory papillae morphology MP:0006256 as an additional parent
