### ISSUE TITLE
MP:0008511 and others new synonyms + many inconsistencies

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3726]
**MP:0008511 decreased retina inner nuclear layer thickness**
new synonyms _decreased retinal INL thickness | reduced retina INL thickness | reduced retinal INL thickness | thin retina INL | thin retinal INL_
or at least one of those synonyms so that search for INL brings up the term.

Similar for all other terms that use _retinal inner nuclear layer._

**MP:0008582 short photoreceptor inner segment**
new synonym _thin photoreceptor inner segment_

**MP:0008587 short photoreceptor outer segment**
new synonym _thin photoreceptor outer segment_

**MP:0020812 long photoreceptor outer segment**
new synonym _thick photoreceptor outer segment_

Also, 
**MP:0008513 thin retina inner plexiform layer
MP:0008519 thin retina outer plexiform layer
MP:0008515 thin retina outer nuclear layer
MP:0008507 thin retina ganglion layer**
vs
**MP:0008511 decreased retina inner nuclear layer thickness**

Same for thick vs increased thickness.

Also, **MP:0006303 abnormal retina nerve fiber layer morphology** is the only childless daughter term. 

Also,
**MP:0003729 abnormal photoreceptor outer segment morphology**
-> **MP:0020811 abnormal photoreceptor outer segment size**
->> **MP:0020812 long photoreceptor outer segment**
->> **MP:0008587 short photoreceptor outer segment**
vs
**MP:0003730 abnormal photoreceptor inner segment morphology**
-> **MP:0008582 short photoreceptor inner segment**
(also, no long)

**Comment by sbello** [comment]
added the INL synonyms

Given that the definition for short photoreceptor inner segment specifies 'length' I do not think 'thin' is a correct synonym. Typically thin is used for decreased width.

**Comment by sbello** [comment]
added long photoreceptor inner segment (MP:0014247)

**Comment by LaurensWilming** [comment]
That’s not quite true: though it is stupid (IMHO), for some reason the thickness in (some) retinal layers is referred to as length. So, long and short are equivalent to what a normal person would call thick and thin. Note that for those layers that use short/long terms, there are no thin/thick terms because long/short means thick/thin…

**Comment by sbello** [comment]
The inner segments aren't a layer these are part of a cell.
See https://en.wikipedia.org/wiki/Photoreceptor_cell
It is possible for the segment to be shorter (decreased length) but thicker (increased width).
Could you give me an example of a layer that is using short/long?

**Comment by LaurensWilming** [comment]
Maybe create synonyms then phrased as "thin photoreceptor outer segment layer (PROS)" (equivalent for the others)? Because if you have long outer segments then the outer segment layer is thick.

See for example PMID:28559716 and https://bjo.bmj.com/content/99/10/1323
