### ISSUE TITLE
MP:0013609 Medullar ovarian follicles?

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3740]
MP:0013609 _abnormal ovarian medulla morphology_ specifically states "**it does not contain any ovarian follicles**". PMID:35906245 mentions medullar follicles and cortical follicles.
I don't know enough about ovarian histology, but it's worth checking.

**Comment by sbello** [comment]
Additional references indicating follicles in the medulla
https://pubmed.ncbi.nlm.nih.gov/21112953/

The MP definition is taken from Gray's anatomy I think.  Although this also repeats that all follicles are in the cortex https://histology.siu.edu/erg/ovary.htm 

I removed the reference to absence of follicles as I don't think this is essential to the definition and appears if not wrong then at least unclear or possibly species specific.
