### ISSUE TITLE
ribosome terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3747]
From Melissa:
I have a mutation that causes impaired ribosome assembly. I look up “ribosom” in the MP and only get abnormal ribosomal stalling. Seems like there should be more terms related to something as central as a ribosome, eh? What am I missing/mis-labelling? 

Looking at existing annotations I think this is due to not that many annotations for ribosome phenotypes. Looking at abnormal cell morphology I only see 5 or 6 notes mentioning ribosomes and for abnormal cell physiology there are only 2 or 3. 

We could add:
abnormal ribosome morphology
abnormal ribosome physiology
    abnormal ribosome biogenesis (I see notes mentioning this under both morphology and physiology so a term could help with consistency) see GO:0042254
        abnormal ribosome assembly - see GO:0042254

**Comment by sbello** [comment]
abnormal ribosome morphology - MP:0014238
abnormal ribosome physiology - MP:0014240
abnormal ribosome biogenesis - MP:0014242
abnormal ribosome assembly - MP:0014243
abnormal intracellular organelle morphology - MP:0014239
abnormal intracellular organelle physiology - MP:0014241
added the intracellular organelle terms and moved the new and existing intracellular organelle terms under these

**Comment by sbello** [comment]
reviewing other annotations to cell morphology and cell physiology for new child terms:
added 
abnormal cellular ATP level - MP:0014244
decreased cellular ATP level - MP:0014246
increased cellular ATP level - MP:0014245

**Comment by sbello** [comment]
consider adding terms for 
endosome (GO:0005768 )
centrosome (GO:0005813 )

**Comment by anna-anagnostop** [comment]
May want to add terms for 
nuclear envelope GO:0005635

**Comment by sbello** [comment]
no annotations to move to:
endosome (GO:0005768 )
centrosome is already in

**Comment by sbello** [comment]
I think we can close this. We can create a new ticket if we get enough annotations to add more terms.
