### ISSUE TITLE
Review miotic pupils 

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#3766]
Existing MP term: 
miotic pupils [MP:0002003](https://www.informatics.jax.org/vocab/mp_ontology/MP:0002003) 
Current definition: contraction of the pupils
Current synonyms: abnormal pupil constriction | meiotic pupils | myotic pupils 

[MP:0002003](https://www.informatics.jax.org/vocab/mp_ontology/MP:0002003) is currently under [abnormal pupil morphology](https://www.informatics.jax.org/vocab/mp_ontology/MP:0002003#).

The HPO term Miosis[ HP:0000616](https://www.informatics.jax.org/vocab/hp_ontology/HP:0000616) is defined as "Abnormal (non-physiological) constriction of the pupil." and placed under physiology ([Abnormal pupillary function](https://www.informatics.jax.org/vocab/hp_ontology/HP:0007686)). 

Both the MP and HPO term use the same EQ i.e., abnormalConstrictionOfAnatomicalEntity pattern using PATO term constricted [PATO:0001847](http://purl.obolibrary.org/obo/PATO_0001847) (which is under **morphology**).

If the intent of the HPO term is to describe the process that results in miotic pupils (i.e. there is a problem with the iris sphincter muscles or the nerves that control them) and not the morphological endpoint, then the HPO EQ should use something like excessive muscle contraction and located in the iris.

1. Consider modifying MP:0002003 definition based on opposite MP term (mydriasis MP:0002546) to read as “decreased diameter of one or both central circular aperture of the iris through which light rays enter the eye” 
Comment: Miosis is a condition in which the pupils of the eyes are always too small, whether in light or dark. Pupils are considered abnormal if they do not dilate in the dark and if they do not constrict in brightly lit conditions. https://myvision.org/eye-conditions/miosis/

2. Place MP:0002003 under small pupils MP:0001320 
Add new synonyms: pinpoint pupils (narrow)| pupillary miosis (exact) | constricted pupils (exact) | pupillary constriction (exact)

Check [annotation](http://bhmgiapp01.jax.org/usrlocalmgi/live/qcreports_db/pwi/#ALL_MPChild.py%7CMP%3A0001320)s to small pupils MP:0001320 
Check [annotations](http://bhmgiapp01.jax.org/usrlocalmgi/live/qcreports_db/pwi/#ALL_MPChild.py%7CMP%3A0002003) to miotic eyes MP:0002003
Check [annotations](http://bhmgiapp01.jax.org/usrlocalmgi/live/qcreports_db/pwi/#ALL_MPChild.py%7CMP%3A0002638) to abnormal pupillary reflex MP:0002638

**Comment by sbello** [comment]
"decreased diameter of one or both pupils due to abnormal constriction of the muscles of the iris ”
