### ISSUE TITLE
oval and round window child terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3779]
for oval window we have only absent, consider adding increased/decreased size (J:220430)
for round window we have absent and small but not large/increased size

**Comment by sbello** [comment]
I see this term in the MP file but for some reason it did not make it into the file in MGI. Reopening until I figure out what happened.

**Comment by anna-anagnostop** [comment]
Sue, regarding increased round window size MP:0031493, I had erroneously inserted my ORCID # under has_obo_namespace. Changed that to MPheno.ontology. Let's see if this change rectifies the issue.

**Comment by sbello** [comment]
Going to do a new build and release today to push to MGI. I think removing the namespace will fix it.

**Comment by anna-anagnostop** [comment]
@sbello:
FYI, I checked on production 8/1/2023 and found increased round window size MP:0031493 in the PWI. Looks this issue is now resolved.
