### ISSUE TITLE
abnormal cornea size

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3780]
add terms for abnormal/increased/decreased cornea size

**Comment by anna-anagnostop** [comment]
Added new  terms:

abnormal cornea size MP:0031498
DEF: deviation from the average range of cornea size for a given organism
SYN: abnormal corneal size

decreased cornea size MP:0031499
DEF: reduced average size of one or both corneas; generally refers to a congenital defect
SYN: microcornea
SYN: small cornea
SYN: small corneas
SYN: reduced cornea size
SYN: decreased corneal size
SYN: reduced corneal size

increased cornea size MP_0031500
DEF: increased average size of one or both corneas
SYN: increased corneal size
SYN: macrocornea
SYN: megalocornea
SYN: enlarged cornea
SYN: enlarged corneas
SYN: large cornea
SYN: large corneas

**Comment by sbello** [comment]
need to make thickness a child of size
