### ISSUE TITLE
abnormal vision

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3791]
abnormal vision MP:0002090 
current definition 'inability or decreased ability to see' is too narrow
should be 'any anomaly in the ability to see'

also add under abnormal visual acuity:
increased visual acuity

**Comment by anna-anagnostop** [comment]
Amended definition for abnormal vision MP:0002090 to read as 'any anomaly in the ability to see'

Added new term:
increased visual acuity MP_0031497
DEF: gain in visual acuity or increased ability to distinguish small details
