### ISSUE TITLE
motor delay

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3792]
consider adding a term for 
motor developmental delay
child of behavioral developmental delay
see Motor delay (HP:0001270)
def in HPO "A type of Developmental delay characterized by a delay in acquiring motor skills."
several annotations to behavioral developmental delay that could be moved to this

related to CHARGE syndrome HPO phenotypes

**Comment by anna-anagnostop** [comment]
Added new term:
motor developmental delay MP:0031496
DEF: acquisition of motor skills or milestones, including gross and/or fine motor abilities, occurs later in development compared to controls
SYNONYMS: delayed early motor milestones | delayed motor development | delayed motor milestones | delay in motor development | locomotor delay | motor retardation | delayed development of motor milestones | retarded motor development
