### ISSUE TITLE
short limbs child terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3793]
consider adding child terms for 'short limbs'
HPO has many child terms of Limb undergrowth (HP:0009826) that could be applicable

annotations to short limbs mention
rhizomelic (2)
distal shortening
hindlimb only
forelimb only

**Comment by anna-anagnostop** [comment]
Review parent/child relation of micromelia MP:0008736 and short limbs MP:0000547 

micromelia MP:0008736 
CURRENT DEF: disproportionately short or small limbs
CURRENT SYN: nanomelia 

Questions: 

- remove disproportionately from definition?
- make nanomelia a narrow synonym?
- Micromelia occurs when the shortening affects both the proximal and distal bones equally see https://www.sciencedirect.com/topics/medicine-and-dentistry/micromelia

**Comment by anna-anagnostop** [comment]
Alternative definitions for rhizomelia  and mesomelia from https://link.springer.com/chapter/10.1007/978-3-642-54610-5_13
"The term rhizomelic pertains to the proximal portions of the limbs including shoulder and arm in the upper extremity and hip and thigh in the lower extremity. Rhizomelia is defined as either a disproportion of the length of the proximal limb usually shortening or deformity affecting the shoulder and arm or hip and thigh. The term mesomelic pertains to the middle portions of the limbs including forearm and leg. Mesomelia is defined as a condition in which the forearms and lower legs are abnormally short or deformed. "

**Comment by sbello** [comment]
added rhizomelic limb with rhizomelia as synonym since in some definitions rhizomelia is used more as a disease term to cover multiple phenotypes (MP:0014288)
added
decreased distal limb length MP:0014289
