### ISSUE TITLE
placement of abnormal erythrocyte sedimentation rate

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3817]
For some reason abnormal erythrocyte sedimentation rate is sitting under abnormal circulating mineral level
This seems incorrect to me. Need to review why this term is located here

**Comment by anna-anagnostop** [comment]
Current placement under abnormal circulating mineral level is incorrect. 

Looks like abnormal erythrocyte sedimentation rate should be placed under "abnormal blood homeostasis" MP:0009642 (as originally requested in[ #3201](https://github.com/mgijax/mammalian-phenotype-ontology/issues/3201)).

Additional parent terms may include:

- [ ] abnormal erythrocyte physiology MP:0003656  
- [ ] possibly, abnormal inflammatory response MP:0001845 ?

**Comment by anna-anagnostop** [comment]
Moved abnormal erythrocyte sedimentation rate under "abnormal blood homeostasis" MP:0009642

**Comment by anna-anagnostop** [comment]
Left only under "abnormal blood homeostasis" MP:0009642. Additional parents were discussed and rejected (term is unspecific; phenotype has too many causes to pin it down to one).
