### ISSUE TITLE
placement of round window

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3819]
MP has round window terms under middle ear, foramen and temporal bone petrous part

HPO has this under middle and inner ear

MP uses http://purl.obolibrary.org/obo/UBERON_0002502 in the EQ so it seems odd to not have this under inner ear. 

Looking in Uberon this is under foramen of skull and petrous part of temporal bone but not under ear at all

Need to review the placement of this, at the least I think moving it out from under middle ear or adding the inner ear parent may be needed

**Comment by sbello** [comment]
Looking at diagrams in Wikipedia it seems correct to have this as middle https://en.wikipedia.org/wiki/Round_window

**Comment by sbello** [comment]
MP should add this to inner ear as well

**Comment by anna-anagnostop** [comment]
abnormal round window morphology MP:0004480 (and child terms) has been additionally placed under abnormal inner ear morphology MP:0000026.
