### ISSUE TITLE
new synonym for MP:0003772 lip pits

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3825]
new synonym for **MP:0003772 lip pits**
_lip notches_

PMID:37075751

Associate lip pits with PMID: 25201852 as cross -ref

**Comment by anna-anagnostop** [comment]
@LaurensWilming @sbello 
Looking at PMID: 37075751 (J:335489), the median lip notch shown in Figure S8E represents a (mild case of) midline cleft upper lip MP:0031445.

**Comment by anna-anagnostop** [comment]
median lip notch should be a narrow synonym of midline cleft upper lip MP:0031445.

**Comment by sbello** [comment]
https://ijdvl.com/congenital-lip-pits-without-associated-anomalies/

**Comment by anna-anagnostop** [comment]
Lip notches are not equivalent to lip pits.

Changed primary term label for MP:0003772 to use singular form “lip pit”, used plural form as a synonym, added PMID:25201852 as a db cross-ref, and added rdfs:comment "A lip pit is distinct from a cleft lip or a lip notch which may represent a mild case of cleft lip."

Added "median lip notch" as a narrow synonym of midline cleft upper lip MP:0031445.
