### ISSUE TITLE
split abnormal heart shape

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3829]
add child terms to abnormal heart shape 

at the least add globular heart shape, many existing annotations reference globular, globose, or round heart shape

ref - J:338912

**Comment by anna-anagnostop** [comment]
Use "spheroid" in the EQ?
See discussion for the globozoospermia EQ ([#3518)](https://github.com/mgijax/mammalian-phenotype-ontology/issues/3518) - decision to use "spheroid" (a convex 3-D shape), not circular" (a 2-D shape) or "spherical" (where equatorial diameter is equal to the polar diameter)

**Comment by anna-anagnostop** [comment]
Term label is ok, use globular heart.
Add all suggested synonyms as EXACT.
Do NOT add an EQ.

**Comment by anna-anagnostop** [comment]
Added new term:
globular heart MP:0031511 (under abnormal heart shape MP:0000277)
