### ISSUE TITLE
children for MP:0021158 decreased heart left ventricle wall thickness to be equal with MP:0021157

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3831]
**MP:0021158 decreased heart left ventricle wall thickness** currently has no children. **MP:0021157 increased heart left ventricle wall thickness** has 3 children. Therefore MP:0021158 should bear 3 child terms too.

**Comment by sbello** [comment]
term only has 6 annotations, I suspect the increased child terms were added by request as only one of these is in use

**Comment by LaurensWilming** [comment]
I specifically need reduced left ventricular posterior wall thickness

**Comment by sbello** [comment]
Okay @LaurensWilming I'll get the new terms in as soon as possible, hopefully tomorrow
