### ISSUE TITLE
MP:0005335 and children: epigonadal synonym

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3836]
MP:0005335 abnormal gonadal fat pad morphology
add synonym: **abnormal epigonadal fat pad morphology**
MP:0009283 decreased gonadal fat pad weight
add synonym: **decreased epigonadal fat pad weight**
MP:0009285 increased gonadal fat pad weight
add synonym: **increased epigonadal fat pad weight**

As per PMID:34390703

**Comment by anna-anagnostop** [comment]
epigonadal specifically refers to above the gonads, see https://en.wiktionary.org/wiki/epigonadal
Added "epigonadal" as a narrow synonym to MP:0005335, MP:0009283 and MP:0009285  (see Glossary in PMID:33148396)
