### ISSUE TITLE
MP:0011380 enlarged brain ventricles new synonym ventriculomegaly

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3888]
MP:0011380 enlarged brain ventricles
Synonym: **ventriculomegaly**

See J:342770

**Comment by anna-anagnostop** [comment]
Brain ventriculomegaly and ventriculomegaly of the brain have been added as exact synonyms (to distinguish from heart ventricles). 
Ventriculomegaly has been added as a broad synonym.
