### ISSUE TITLE
new terms under MP:0000313 abnormal cell death: necroptosis, pyroptosis and ferroptosis

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3897]
>1. Preferred term label

**abnormal necroptosis** 
and any appropriate children (increased, decreased)
**abnormal pyroptosis**
and any appropriate children (increased, decreased)
**abnormal ferroptosis**
and any appropriate children (increased, decreased)

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

PMID:35064213

https://doi.org/10.1016/j.jmb.2021.167378
https://www.ptglab.com/news/blog/what-is-the-difference-between-pyroptosis-and-apoptosis/
https://www.frontiersin.org/articles/10.3389/fcell.2021.789948/full
https://doi.org/10.1038/s41419-020-2298-2

Necroptosis is a type of programmed cell death that combines necrosis and apoptosis. Necroptosis is thought to be a secondary cell death response to situations where apoptosis is inhibited. Necroptotic death releases molecules that promote inflammation, a process referred to as necroinflammation.

Pyroptosis is generally a primary response to infectious organisms. Pyroptosis represents a form of cell death that is triggered by proinflammatory signals and associated with inflammation. Pyroptosis is a proinflammatory form of regulated cell death.

Ferroptosis is an intracellular iron-dependent form of cell death that is distinct from apoptosis, necrosis, and autophagy. Ferroptosis does not result in morphological changes similar to the chromatin condensation that occurs during apoptosis, the loss of plasma membrane integrity that occurs during necrosis, or the formation of double membrane‐layered autophagic vacuoles that occurs during autophagy.

>5. Suggested parent term 

**MP:0000313 abnormal cell death**

**Comment by anna-anagnostop** [comment]
see also  #2669
