### ISSUE TITLE
new parent terms for kidney glutathione reductase

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3916]
decreased kidney glutathione reductase level
increased kidney glutathione reductase level

currently only under homeostasis, should also be under kidney morphology

**Comment by anna-anagnostop** [comment]
Need to search Protege for abnormal X [tissue] level for the following tissues:

- [ ] liver
- [ ] muscle
- [ ] brain
- [ ] heart 
- [ ] intestine
- [ ] kidney
- [ ] nervous system
- [ ] erythrocyte
- [ ] pancreas
- [ ] spleen
- [ ] adipose tissue
- [ ] platelet
- [ ] lung

**Comment by anna-anagnostop** [comment]
All abnormal X level terms identified have been additionally placed under the appropriate abnormal X morphology parent term.
