### ISSUE TITLE
new child terms for MP:0013708 abnormal hematopoietic precursor cell number

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3923]
new child terms for MP:0013708 abnormal hematopoietic precursor cell number

>1. Preferred term label

_decreased hematopoietic precursor cell number_
child: _absent hematopoietic precursor cell number_
_increased hematopoietic precursor cell number_

Synonyms and definitions mimicking those of parent term.

In general, all "abnormal .... number" terms should have "decreased" and "increased" children. For that matter, so should any "abnormal .... thickness" and similar quantifiable terms.

**Comment by sbello** [comment]
added 
increased - MP:0014400
decreased - MP:0014399
absent - MP:0014401
