### ISSUE TITLE
abnormal susceptibility to age-related retinal degeneration

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3930]
Create new terms for number abnormal/increased/decreased susceptibility to age-related retinal degeneration as there are a number of ‘resistance to age-related retinal degeneration’ currently annotated to retinal degeneration (MP:0001326 ) and that just isn’t right.

This term would be a child of abnormal retina morphology (MP:0001325)

**Comment by sbello** [comment]
There are also a set of just 'resistant to retinal degeneration' so we should have a more generic parent of abnormal/increased/decreased susceptibility to retinal degeneration

**Comment by anna-anagnostop** [comment]
Added new terms:

abnormal susceptibility to age-related retinal degeneration MP:0031604
DEF: a change in the likelihood that an organism will develop retinal degeneration that is progressive with age
SYN: altered susceptibility to age-related retinal degeneration

decreased susceptibility to age-related retinal degeneration MP:0031605
DEF: less likely than normal to develop retinal degeneration that is progressive with age
SYN: increased resistance to age-related retinal degeneration
SYN: reduced susceptibility to age-related retinal degeneration

increased susceptibility to age-related retinal degeneration MP:0031606
DEF: more likely than normal to develop retinal degeneration that is progressive with age
SYN: decreased resistance to age-related retinal degeneration
SYN: reduced resistance to age-related retinal degeneration
