### ISSUE TITLE
add skeletal muscle glucose uptake terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3942]
We have terms for muscle in general and cardiac muscle but not for skeletal muscle glucose uptake, we should add abnormal/increased/decreased terms

**Comment by anna-anagnostop** [comment]
Changed primary term label for abnormal cardiac cell glucose uptake MP:0004039 (and child terms decreased cardiac cell glucose uptake MP:0030020 and increased cardiac cell glucose uptake MP:0030018) to "cardiac muscle cell glucose uptake" to be in sync with existing EQs.

Added new terms:

abnormal skeletal muscle cell glucose uptake MP:0031617
decreased skeletal muscle cell glucose uptake MP:0031618
increased skeletal muscle cell glucose uptake MP:0031619

EQ of all  new terms use
