### ISSUE TITLE
add terms for abnormal/increased/decreased muscle glycogen levels

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3943]
We have cardiac and skeletal glycogen level terms but not a generic term for muscle levels

J:345630 - has the phenotype decreased muscle glycogen level

**Comment by anna-anagnostop** [comment]
We already have abnormal muscle glycogen level MP:0014068. Changed EQ to use 'muscle tissue' instead of 'muscle organ' for consistency with child terms' EQs.

'has part' some 
    (amount
     and ('characteristic of' some 
        (glycogen
         and ('part of' some 'muscle tissue')))
     and ('has modifier' some abnormal))

Added:
decreased muscle glycogen level MP:0031615
increased muscle glycogen level MP:0031616
