### ISSUE TITLE
New in/decreased child terms for MP:0008721, MP:0010209, MP:0008713 and MP:0010210

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3951]
_MP:0008721 abnormal chemokine level
MP:0010209 abnormal circulating chemokine level
MP:0008713 abnormal cytokine level
MP:0010210 abnormal circulating cytokine level_
and probably many others could do with nonspecific 
**increased ..... level**
**decreased ..... level**
Currently, only specified chemo/cytokines have in/decreased child terms.

**Comment by sbello** [comment]
I think this is done
