### ISSUE TITLE
abnormal intromission

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3974]
New term request from Melissa

abnormal intromission
J:346340 PMID:[3593827](https://pubmed.ncbi.nlm.nih.gov/3593827/)
J:38600 PMID:[9037078](https://pubmed.ncbi.nlm.nih.gov/9037078/)

definition 
any anomaly in the insertion of the penis into the vagina
https://www.sciencedirect.com/topics/medicine-and-dentistry/intromission 
child of abnormal sexual interaction MP:0002566

Also add a term for 
abnormal mounting behavior
need to work on definition
need to review annotations to see if we should add child terms or additional terms

**Comment by anna-anagnostop** [comment]
abnormal intromission
Add synonym: abnormal intravaginal penile insertion

I think abnormal intromission and abnormal mounting behavior terms should be placed under abnormal copulation MP:0009697. 

How does abnormal sexual interaction MP:0002566 relate to abnormal copulation MP:0009697 ?

Per PMID: [37324524](https://pubmed.ncbi.nlm.nih.gov/37324524) (focusing on Male rat sexual behavior):

2.1. Description: Male rat copulatory pattern is shaped by three distinct motor behaviors ([Figure 1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10264596/figure/F1/)): (i) mounting behavior, during which the male puts its forepaws on the female’s flanks and shows pelvic thrusting, without accomplishing vaginal penile insertion; (ii) intromission behavior, consisting of a mount during which the male presents pelvic thrusting, penile erection, and attains intravaginal penile insertion and (iii) ejaculatory behavior, consisting of an intromission of longer duration during which seminal emission occurs (for a detailed description see [Hull and Rodríguez-Manzo, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10264596/#B73)).

2.2. Male sexual behavior physiological mechanisms: Copulation itself represents the consummatory component of sexual behavior, which is shaped by three distinct sexual motor responses, i.e., mount, intromission and ejaculation

**Comment by anna-anagnostop** [comment]
Added new terms:
abnormal intromission MP:0031628
abnormal mounting behavior MP:0031629
