### ISSUE TITLE
abnormal chromatoid body morphology

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3976]
Add new term: abnormal chromatoid body morphology
child of abnormal male germ cell morphology (MP:0006362)
any structural anomaly in the ribonucleoprotein complex found in the cytoplasm of male germ cells, composed of exceedingly thin filaments that are consolidated into a compact mass or into dense strands of varying thickness that branch to form an irregular network
GO:0033391 
PMID:38470475

existing annotations under MP:0006380 and MP:0006362

**Comment by anna-anagnostop** [comment]
Added new term: abnormal chromatoid body morphology MP:0031620

**Comment by anna-anagnostop** [comment]
Reopened issue to address whether new term should also be placed under abnormal intracellular organelle morphology MP:0014239

**Comment by anna-anagnostop** [comment]
MP:0031620 has also been placed under abnormal intracellular organelle morphology MP:0014239
