### ISSUE TITLE
dental pulp necrosis and tooth physiology in general

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3978]
dental pulp necrosis is sitting under abnormal dental pulp morphology but most other necrosis terms are under physiology
also has as a parent cellular necrosis which means this term is sitting under both morphology and physiology

There doesn't appear to be a good place to put any tooth physiology terms currently. All tooth related terms are on the morphology branch.

PMID:38105557 reports increased apoptosis in the dental pulp 

Consider adding terms for: 
abnormal tooth physiology
  parent term abnormal skeleton physiology
abnormal/increased/decreased dental pulp cell apoptosis

move dental pulp necrosis to sit under abnormal tooth physiology

**Comment by sbello** [comment]
actually most terms are under both morphology and physiology - only bone necrosis was purely phys

removed EQ from cellular necrosis as this points to an obsolete GO term

many tissue terms are defined as "morphological changes resulting from pathological death of X"

So should we remove the tissue terms from under cellular necrosis and just leave these under morphology?

**Comment by anna-anagnostop** [comment]
After removal of all tissue terms from under cellular necrosis, only terms left under cellular necrosis are gangrene and dry gangrene.

Added necrotic X as a synonym where missing
