### ISSUE TITLE
new synonyms for abnormal dental pulp canal morphology and abnormal dental pulp chamber morphology

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3979]
PMID:38105557 uses coronal and radicular as synonyms for pulp chamber and pulp canal, respectively we should add the synonyms

abnormal coronal pulp chamber morphology for abnormal dental pulp chamber morphology

abnormal radicular pulp morphology for abnormal dental pulp canal morphology

also the tow terms have child terms for enlarged but not for decreased so we should add those

**Comment by anna-anagnostop** [comment]
Synonyms have been added, as suggested above.

Also added:
small dental pulp chamber MP:0031621
small dental pulp canal MP:0031622
