### ISSUE TITLE
divide decreased ventricle muscle contractility MP:0005598 

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3987]
Divide decreased ventricle muscle contractility MP:0005598 into left and right terms.

This term has 228 annotations and 315 notes

175 notes mention left 
11 notes mention right

**Comment by anna-anagnostop** [comment]
Changed primary label of decreased ventricle muscle contractility [MP:0005598](http://www.ebi.ac.uk/ols4/ontologies/mp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMP_0005598) to include “heart” → decreased heart ventricle muscle contractility (for consistency with other terms)

Added new terms:
decreased heart left ventricle muscle contractility MP:0031633
decreased heart right ventricle muscle contractility MP:0031634

Also, changed primary label of increased ventricle muscle contractility [MP:0005600](http://www.ebi.ac.uk/ols4/ontologies/mp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMP_0005600) to include “heart” → increased heart ventricle muscle contractility.

Added new terms:
increased heart left ventricle muscle contractility MP:0031635
increased heart right ventricle muscle contractility MP:0031636
