### ISSUE TITLE
add terms for increased/decreased lung cholesterol level lung

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3992]
add terms for abnormal/increased/decreased lung cholesterol level lung
child of abnormal cholesterol level MP:0003947 and abnormal lung morphology
PMID:37890669
existing annotations under increased cholesterol level

**Comment by anna-anagnostop** [comment]
Added new terms:
abnormal lung cholesterol level MP:0031630
decreased lung cholesterol level MP:0031631
increased lung cholesterol level MP:0031632
