### ISSUE TITLE
add terms for thick/thin pulmonary alveolus wall

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3993]
add terms for thick/thin pulmonary alveolus wall

increased/decreased pulmonary alveolus wall thickness

child of abnormal pulmonary alveolus wall morphology MP:0010903 
PMID:37890669 and a number of existing annotations

**Comment by anna-anagnostop** [comment]
Reopening issue to fix typo in the textual definition of MP:0010903 and its new child terms.

For MP:0010903, current definition reads as: any structural anomaly in the tissue that encloses the **_aveolar_** space of the lung. This is propagated in the increased/decreased pulmonary alveolus wall thickness terms. Change to "alveolar".

**Comment by anna-anagnostop** [comment]
Typo has been fixed.
