### ISSUE TITLE
why are MP:0003122 maternal imprinting and MP:0003123 paternal imprinting phenotypes?

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3995]
Why are _MP:0003122 maternal imprinting_ and _MP:0003123 paternal imprinting_ phenotypes? Maternal and paternal imprinting is supposed to happen! If it doesn't, you're in big trouble.
So it should really be:
**MP:0003122 abnormal maternal imprinting
MP:0003123 abnormal paternal imprinting**
as children of 
**MP:0003787 abnormal imprinting**
with the definitions updated accordingly.

Or am I missing something?

**Comment by sbello** [comment]
maternal and paternal imprinting were added back when MGI decided not to have maternal and paternal versions of alleles. These are meant to indicate that the phenotypes of the mouse vary with maternal/paternal inheritance. Really these shouldn't be phenotypes but we stuck this in to be able to find these types of genotypes. Much like 'no phenotypic analysis' it would be good to come up with a different solution and obsolete these terms.

**Comment by sbello** [comment]
removed the parent 'abnormal epigenetic regulation of gene expression'

**Comment by sbello** [comment]
genetic imprinting is defined as abnormal but the label could be interpreted as normal and this has an abnormal imprinting child term. I believe this was intended to be a normal

**Comment by anna-anagnostop** [comment]
Modified textual def of genetic imprinting to "the process that modulates the frequency, rate or extent of the chemical reactions and pathways involving macromolecules by a mechanism that is mediated by DNA, is mitotically or meiotically heritable, or is stably self-propagated in the cytoplasm of a resting cell, and does not entail a change in DNA sequence" to match the term label better
