### ISSUE TITLE
steatorrhea eq

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3998]
Both MP and HP have a term "steatorrhea"
MP definition - passage of large amounts of fat in the feces due to the inability to digest and absorb it
HP definition - Greater than normal amounts of fat in the feces. This is a result of malabsorption of lipids in the small intestine and results in frothy foul-smelling fecal matter that floats.

I think these are intended to be the same phenotype but they have different eqs and I don't think either is correct.

MP - 'has part' some 
('increased amount' and ('characteristic of' some 
(lipid and ('part of' some feces))) and ('has modifier' some abnormal))
I think this is too broad, the intent of steatorrhea I think is more 'excessive total lipid'. We would not want to say that feces with an increase in some type of lipid - say bile salts is a child of steatorrhea but we would want to say that it is a child of increase feces lipid level as this typically just means an increase in some lipid

HP - [has part](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051?lang=en)some([increased amount](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000470?lang=en)[pato](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000470)and[characteristic of](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0000052?lang=en)[ro](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0000052)some([adipose tissue](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001013?lang=en)[uberon](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001013)and[part of](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050?lang=en)[ro](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050)some[feces](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001988?lang=en)[uberon](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001988))and[has modifier](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002573?lang=en)[ro](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002573)some[abnormal](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000460?lang=en)[pato](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000460))
 not sure why this is using 'adipose tissue' it isn't isn't the tissue but lipids in general in the feces

Should discuss this at the next MP-HP call

**Comment by anna-anagnostop** [comment]
We should also discuss placement. 

MP places steatorrhea under abnormal feces composition which is under "abnormal digestive system physiology".

HPO places steatorrhea under "Fat malabsorption" which is a child of both "Abnormal small intestine morphology" and "Malabsorption" (under "Abnormality of digestive system physiology").

Note that fatty [PATO:0002114](http://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0002114), defined as "A composition quality inhering in a bearer by virtue of the bearer's containing excess lipid", is under "composition" which  is a child of "structure". So using fatty in the EQ would disconnect steatorrhea from digestive system physiology.

**Comment by sbello** [comment]
Discussed at the MP-HP meeting 7/18/24 plan is to

- remove the EQ from the MP term
- add new parent class of increased feces lipid level 
- add mapping of MP-HP steatorrhea terms to the SSSOM file
