### ISSUE TITLE
abnormal cortical ventricular zone morphology MP:0008458

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#4020]
Divide abnormal cortical ventricular zone morphology add new children

abnormal/increased/decreased cortical ventricular zone thickness
PMID:38331934 and existing annotations

abnormal/increased/decreased cortical ventricular zone cell density
existing annotations

review annotations further for other child terms to add

**Comment by anna-anagnostop** [comment]
Currently, one of the synonyms for increased cortical ventricular zone thickness MP:0014557 is "thin cortical ventricular zone'; synonym should be changed to "thick cortical ventricular zone'.
