### ISSUE TITLE
abnormal egg cylinder size terms

### ISSUE THREAD

**Issue by anna-anagnostop** [mgijax/mammalian-phenotype-ontology#4030]
Need to create new child terms of abnormal egg cylinder morphology MP:0003085, including:

abnormal egg cylinder size / decreased egg cylinder size / increased egg cylinder size

**Comment by sbello** [comment]
several annotations refer to failure of/defect in elongation - should we add a term for this or group these with 'small'
we do have a term for abnormal primitive streak elongation  
the question I have is when they talk about impaired elongation is that really just another way to say small?

**Comment by sbello** [comment]
added abnormal/increased/decreased size terms

**Comment by anna-anagnostop** [comment]
See PMID: [36252218](https://pubmed.ncbi.nlm.nih.gov/36252218/) and PMID: [32433954](https://pubmed.ncbi.nlm.nih.gov/32433954/) for info on mouse egg-cylinder morphogenesis

**Comment by sbello** [comment]
add rudimentary egg cylinder as a narrow synonym for small

**Comment by anna-anagnostop** [comment]
test
