### ISSUE TITLE
review placement of organ tumor terms

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#4035]
Some incidence in specific tissue tumor terms are under both neoplasia and the tissue morphology branches while others are only under neoplasia. We should review these and make sure they are consistent.

Example

- increased pancreas tumor incidence only under neoplasia
- increased mammary gland tumor incidence under neoplasia and mammary gland morphology

**Comment by sbello** [comment]
What is the 'reticulum' in the term 'decreased reticular tumor incidence' MP:0020197 definition is:
less than the expected number of neoplams in the reticulum, usually in the form of a distinct mass, in a specific population in a given time period
Looking in Uberon I find UBERON:0007361 'ruminant reticulum' that has NCIT xref 'reticulum' but this seems wrong as there is a child term 'decreased mononuclear phagocyte tumor incidence' 
There is also stellate reticulum - part of the developing tooth UBERON:0006950 and eye trabecular network (reticulum in synonyms) but these also make no sense with the child term  
There is also an increased incidence term with the same issues
There are no annotations in RGD using either term
Term was entered by @nicolevasilevsky back in 2014 so I'm guessing Nicole has no memory of these either.
Searching pubmed for 'reticular tumor' (no quotes) turns up papers about [Fibroblastic reticular-cell tumor](https://pubmed.ncbi.nlm.nih.gov/38040513/) CL has [reticular cell]( http://purl.obolibrary.org/obo/CL_0000432)  maybe this is what it is? But I don't see mononuclear phagocyte as a decedent of reticular cell so the placement still doesn't make sense 


Do we want to put blood cell specific terms under the cell morphology? Not so sure about this, it makes more sense for organs and tissues but not really for the cells.

**Comment by sbello** [comment]
removed the eq from increased lip tumor incidence - this was using lipoma which is just wrong

several other eqs are using the MP term 'neoplasm' - should these go as well?

**Comment by sbello** [comment]
increased mouth tumor incidence is under alimentary system tumor incidence but mouth morphology is under facial morphology and not under alimentary system, why?

**Comment by sbello** [comment]
why is facial tumor incidence under integument system incidence?

**Comment by nicolevasilevsky** [comment]
@sbello you are correct, I don't have any recollection of the logical definition from 2014! :smile: Those were good times working on MP back then though.

**Comment by sbello** [comment]
obsolete decreased and increased reticular tumor incidence
moved child terms to sit under hemolymphoid
