### ISSUE TITLE
abnormal gastric inhibitory polypeptide

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#4044]
Requested term: abnormal gastric inhibitory polypeptide

Proposed parent: abnormal circulating hormone level

Draft definition: any anomaly in the blood concentration of
this endocrine hormone, secreted by the enteroendocrine K-cells in the mucosa
of the duodenum and jejunum in response to feeding, that stimulates insulin
release to regulate blood glucose and nutrient homeostasis.

Parallel VT term: 
VT:0010916 | blood   gastric inhibitory polypeptide amount

**Comment by anna-anagnostop** [comment]
Reopened issue to add 'glucose-dependent insulinotropic polypeptide' as an exact synonym to 'gastric inhibitory polypeptide' to all relevant terms.
abnormal circulating gastric inhibitory polypeptide level MP:0014581 
decreased circulating gastric inhibitory polypeptide level MP:0014583 
increased circulating gastric inhibitory polypeptide level MP:0014582 
SYNONYM SOURCE: [PR:000007986](https://proconsortium.org/cgi-bin/entry_pro?id=PR_000007986), https://en.wikipedia.org/wiki/Gastric_inhibitory_polypeptide
