### ISSUE TITLE
dendrite branching morphology

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#469]
Please consider adding the term
abnormal dendrite branching morphology
def - any anomaly in the number or structure of divisions of the dendrite
child of abnormal dendrite morphology
Most of the other branching terms in the MP are defined for the branching process but placed under morphology. I've tried to define this for the morphological outcome of the branching process so that the placement under the morphology branch makes more sense.
This phenotype appears in J:111340 and about 10 existing annotations to abnormal dendrite morphology

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/469](https://sourceforge.net/p/obo/mammalian-phenotype-requests/469)

**Comment by sbello** [comment]
added MP:0021090
