### ISSUE TITLE
spinal cord interneuron

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#540]
The paper J98830 looks at dI1-dI6 dorsal interneuron populations. References Helms, A. W. and Johnson, J. E. (2003). Specification of dorsal spinal cord
interneurons. Curr. Opin. Neurobiol. 13, 42-49 (Attached) It would be useful to include these divisions somehow.

Reported by: jbubier

Original Ticket: [obo/mammalian-phenotype-requests/540](https://sourceforge.net/p/obo/mammalian-phenotype-requests/540)

**Comment by sbello** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8459260/
subtypes
dI - dorsal interneurons
spinal interneurons that relay or modulate distinct somatosensory modalities via the release of excitatory or inhibitory neurotransmitters and various neuropeptides

dI1-dI6
dI1 - located ventrally in the dorsal horn, expresses Lhx2, transmits mechanosensory and proprioceptive signals
dI2 - located ventrally in the dorsal horn, expresses Lhx1/5 and Foxd3, transmits mechanosensory and proprioceptive signals
dI3 - located ventrally in the dorsal horn, expresses Isl1 and Tlx3, transmits mechanosensory and proprioceptive signals
dI4 - located in the superficial layers of the dorsal horn, expresses Lhx1/5 and Pax2, transmits  pain, heat, and itch sensing signals
dI5 - located in the superficial layers of the dorsal horn, expresses Tlx3, transmits  pain, heat, and itch sensing signals
dI6 - located ventrally in the dorsal horn, expresses Lhx1/5, Pax2, and Wt1, transmits mechanosensory and proprioceptive signals

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7880285/
dI1, dI2, dI3, dI4/dIL<sub>A</sub>, dI5/dIL<sub>B</sub>, dI6, V0 (3 subtypes D, V, C), V1 (2 subtypes Sp8, R), V2a, V2b, V3

**Comment by sbello** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2847453/
see table 1, fig 3, fig4

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4844028/

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5087618/
Fig 2, fig 4, fig 6 
lists dI6 as a "premotor neuron"

**Comment by sbello** [comment]
https://en.wikipedia.org/wiki/Spinal_interneuron

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7247430/
Table 1
dI - dorsally derived interneurons - dI1-6 plus dILA and dILB
V - ventrally derived interneuons - V0 (D, V, C, G), V1, V2a-d, Vx, V3d, V3v
Renshaw
Ia

**Comment by sbello** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4468382/
Fig 1
Renshaw = subtype of V1
F4 
V0 - "primarily contralateral, with some ipsilateral projecting neurons with inhibitory or excitatory identity that send axons 2–4 spinal segments rostrally" 
     4 subclasses

V1 - appear to control burst durations and comprised of cells defined as Ia inhibitory and Renshaw cells
     75% of V1 interneurons are non-Ia, non-Renshaw subclasses that await characterization

V2 - arise from a progenitor pool just dorsal to the pMN domain and share expression of Lhx3 with the pMN domain
     3 subclasses a, b, c

V3 - send projections predominantly contralaterally and caudally, form glutamatergic connections
    subtypes D, V 
   maybe also Vx Hb9 - "glutamatergic, rhythmically active interneurons", developmental origin unknown

8 dorsal types dI1-6, dIL<sub>A</sub>, dIL<sub>B<sub>
dI1-3 - "dependent on signals from the roof plate and termed Class A"
dI4–6 and dILA and dILB  - "independent of roof plate signals and termed Class B"

**Comment by sbello** [comment]
Spreadsheet of new terms https://docs.google.com/spreadsheets/d/1eSFrBx3nip8MkFNf1IWPC423W4lZ-xKIeDsPCDnite8/edit?usp=sharing
