### ISSUE TITLE
lymph fluid

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#550]
Do we need a term to describe lymph fluid and lymph fluid composition?  We have lymphedema.  

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/550](https://sourceforge.net/p/obo/mammalian-phenotype-requests/550)

**Comment by sbello** [comment]
I don't see any annotations referencing lymph fluid or lymph composition 
closing this
