### ISSUE TITLE
lymph node sinus 

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#551]
Need term for lymph node sinus.  We have a term for medullary sinus (abnormal lymph node medulla [MP:0002348] )

From Wikipedia:
A lymph sinus is a channel within the lymph node lined by the endothelial cells along with fibroblastic reticular cells and allows for smooth flow of lymph through them. Thus, subcapsular sinus is a sinus immediately deep to the capsule, and its endothelium is continuous with that of the afferent lymph vessel. It is also continuous with similar sinuses flanking the trabeculae and within the cortex (cortical sinuses). The cortical sinuses and that flanking the trabeculae drain into the medullary sinuses, from where the lymph flows into the efferent lymph vessel.[1]

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/551](https://sourceforge.net/p/obo/mammalian-phenotype-requests/551)

**Comment by sbello** [comment]
doesn't seem like we need this currently
