### ISSUE TITLE
extracutaneous pigmentation vocab

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#577]
abnormal auditory pigmentation [MP:0009390] needs a definition
consider term change (below with definition)

abnormal otic pigmentation   def.  failure of neural crest-derived melanoblasts to migrate to the ear establishing normal numbers,  distribution, or pigment during development   Syn abnormal auditory pigmentation; abnormal inner ear pigmentation

children
amelanotic otic melanocytes    def. failure of neural crest-derived melanocytes in any of the expected locations of the inner ear to produce pigment

abnormal marginal cell layer   def,
any anomaly in the pigment-producing cells that migrate from the neural crest to epithelial marginal cells during development

abnormal cochlear pigmentation
def.  any anomaly in the pigment-producing cells that migrate from the neural crest during development to the spiral-shaped cavity in the petrous portion of the temporal bone of the inner ear containing nerve endings essential for hearing

children
abnormal vestibular region pigmentation   def.  any anomaly in the pigment-producing cells that migrate from the neural crest to the the utricular wall, the cristae, areas of the semicircular duct, or the endolymphatic duct during development

abnormal strial intermediate cell pigmentation     add Syn abnormal strial vascularis pigmentation

see ~ page 100 pdf Chapter 4 The Pigmentary System:  Physiology and Pathopysiology...

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/577](https://sourceforge.net/p/obo/mammalian-phenotype-requests/577)

**Comment by sbello** [comment]
closing for now we can reopen if we find we need the additional terms
