### ISSUE TITLE
hypothalamus nuclei

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#580]
Need to reorganize and add terms for hypothalamus nuclei.

A place to start:

http://en.wikipedia.org/wiki/Hypothalamus

"periventricular nucleus" a/k/a periventricular region is described in Kandel along with others.

Stedman's has listings on the nuclei in each area to complement Kandel

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/580](https://sourceforge.net/p/obo/mammalian-phenotype-requests/580)

**Comment by sbello** [comment]
added abnormal hypothalamic nucleus morphology MP:0020872, moved other nucleus terms under this
added abnormal arcuate nucleus of hypothalamus morphology MP:0020873
