### ISSUE TITLE
sensory systems  - reevaluate?

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#585]
Some time ago, we discussed moving/merging headers and combining sensory systems.  Perhaps this should be reevaluated.

Linda Washburn wrote:
&gt; In mice,  hyperresponsive to tactile stimuli (J:32781) involves 
&gt; anything  touched or responding but vibrissae.
&gt; 
&gt; I'm annotating sps and this is displayed
&gt; 
&gt; touch/vibrissae
&gt;    hyperresponsive to tactile stimuli (J:32781)
&gt;    noticed prior to seizure suseptibility
&gt; 
&gt; along with this,  correct for the mutation --
&gt; behavior/neurological
&gt;    hyperresponsive to tactile stimuli (J:32781)
&gt;    noticed prior to seizure suseptibility
&gt; 
&gt; I see how it happened in vocab development but it is very inaccurate to 
&gt; have touch/vibrissae displayed where vibrissae  involvement is not 
&gt; stated or implied in the reference.
&gt; 
&gt; (I'd be surprised to see an annotation RE vibrissae noting anything 
&gt; abnormal except length, or  curly vs straight, maybe abnormal color.)
&gt; 
&gt; Of course I have no solution but ----sometime---can we change this just 
&gt; a whisker so there is nolonger an inappropriate display? Touch is fine 
&gt; but "touch/vibrissae" suggests (to me anyway) only touching by 
&gt; vibrissae.  Am I making sense?

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/585](https://sourceforge.net/p/obo/mammalian-phenotype-requests/585)

**Comment by sbello** [comment]
done
