### ISSUE TITLE
placement of 	abnormal response to tactile stimuli

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#645]
Currently abnormal response to tactile stimuli is a child of abnormal mechanical nociception; however, mechanical nociception is limited to painful stimuli while response to tactile stimuli is not. I think these terms should be siblings under abnormal touch/ nociception. Or we may want to consider separating these into abnormal response to touch and abnormal nociception. Mechanical nociception would still be a child of both but other touch responses could be placed only under the touch branch.

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/645](https://sourceforge.net/p/obo/mammalian-phenotype-requests/645)

**Comment by sbello** [comment]
placement has been changed
