### ISSUE TITLE
abnormal motor nerve terminal sprouting

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#662]
Abnormal motor nerve terminal sprouting is currently located under the morphology branch however from the definition this terms seems more like a physiological process. Please consider relocating this term to be a child of abnormal nervous system regeneration.

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/662](https://sourceforge.net/p/obo/mammalian-phenotype-requests/662)

**Comment by sbello** [comment]
GO has collateral sprouting (GO:0048668) with injury related child terms
MP has abnormal collateral sprouting with a child for motor neuron collateral sprouting 
There are currently 12 annotations in MGI for this branch, RGD has 0. 
No need to further split this currently
