### ISSUE TITLE
placement of decreased susceptibility to weight gain

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#776]
I'm wondering if the placement of "decreased susceptibility to weight gain" [MP:0010182] is correct? It is a child under: increased body weight. I get that it is a smaller increase in weight gain, and thus the increased body weight placement but when thinking about this, the mice gain less weight than controls under a certain condition and thus they weigh less, so wouldn't it make sense to have it under decreased body weight? It just seemed confusing to see the term under increased body weight and I wonder if it would be to users? I'm kind of left unsure where it should be. 

Reported by: monikat

Original Ticket: [obo/mammalian-phenotype-requests/776](https://sourceforge.net/p/obo/mammalian-phenotype-requests/776)

**Comment by sbello** [comment]
This has been moved out to under "abnormal susceptibility to weight gain" which is a child of "abnormal body weight"
