### ISSUE TITLE
liver degeneration/regeneration

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#783]
I notice that "abnormal liver regeneration" [ [MP:0002658]  is placed under "abnormal liver physiology" (reasonable) while "liver degeneration" [MP:0003103] is under "abnormal liver morphology.  Seems to me these should be children of the same parent.

Howard

Reported by: hdene

Original Ticket: [obo/mammalian-phenotype-requests/783](https://sourceforge.net/p/obo/mammalian-phenotype-requests/783)

**Comment by sbello** [comment]
This is consistent with the way degeneration and regeneration are handled in the MP
