### ISSUE TITLE
placement of abnormal body wall morphology

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#855]
Please consider relocating the term abnormal body wall morphology (MP:0003385) and its children. These are currently placed under abnormal postnatal growth/weight/body size but I need to annotate a defect in closure of the abdominal wall in embryos. The term abnormal abdominal wall (MP:0003257) seems like the best match (and includes omphalocele, which I would consider a prenatal or perinatal phenotype, as a child) but is currently located under the postnatal branch. I would suggest moving the whole abnormal body wall morphology branch out from under postnatal growth and placing it directly under growth/size phenotype.
Thanks, 
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/855](https://sourceforge.net/p/obo/mammalian-phenotype-requests/855)

**Comment by sbello** [comment]
done
