### ISSUE TITLE
interolivary commissure

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#877]
need terms for hindbrain commissures, in particular the interolivary commissure.  A similar posting is made on adult mouse anatomy tracker.

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/877](https://sourceforge.net/p/obo/mammalian-phenotype-requests/877)

**Comment by sbello** [comment]
MA term is "inferior olivary commissure" MA:0003019
No definition for this term in uberon
Only 1 annotation to abnormal commissure mentions interolivary
closing, will reopen if needed
