### ISSUE TITLE
hyper/hypoplasia term definitions  WAS:heart hyperplasia

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#924]
The current definition of heart hyperplasia is "overdevelopment or increased size of the heart, usually due an increased number of cells" I think the word "usually" should be removed from the definition. Or consider changing the definition to "increase in the number of cells in the heart, usually resulting in an increase in the size of the heart".
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/924](https://sourceforge.net/p/obo/mammalian-phenotype-requests/924)

**Comment by sbello** [comment]
See UPheno pattern https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/HyperplasticAnatomicalEntity.yaml

**Comment by sbello** [comment]
blending of definitions
increase in the number of normal cells in normal arrangement in %s, typically resulting in increased size

**Comment by sbello** [comment]
definition does not work for
myeloid hyperplasia MP:0010373 - should this be increased number?

**Comment by sbello** [comment]
working on hypoplasia terms

terms not using the standard definition:
aorta tubular hypoplasia MP:0010543 - hypoplasia but diffuse narrowing, currently a child of aorta hypoplasia,
