### ISSUE TITLE
review "antral" follicle synonyms

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#945]
Remove "antral" follicle synonyms from secondary ovarian follicle terms. Antral follicles are tertiary follicles.  "preantral" synonyms may be appropriate.

An antral follicle (or tertiary or Graafian follicle) is an ovarian follicle during a certain latter stage of folliculogenesis.

See Also  Pedersen T, Peters H 1968 Proposal for a classification of oocytes and follicles in the mouse ovary. J Reprod Fertil 17:555–557.

Currently:
MP term:    abnormal secondary ovarian follicle morphology
Synonym:    abnormal antral follicle
Synonym:    abnormal folliculus ovaricus vesiculosus
Synonym:    abnormal Graafian follicle
Synonym:    abnormal vesicular follicle
Synonym:    abnormal vesicular ovarian follicle
MP id:  MP:0009363

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/945](https://sourceforge.net/p/obo/mammalian-phenotype-requests/945)

**Comment by sbello** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2761115/ Fig 4
 primordial, primary, secondary, preantral, and antral


https://onlinelibrary.wiley.com/doi/epdf/10.1002/ar.1091840409

"Follicles were counted in each section and scored for the developmental  stage  as described by Peters ('69). Six stages were enumerated in classes as follows: (1) Stage 2, oocyte surrounded by a single layer of squamous follicle  cells (fig. 1); (2) Stage 3, oocyte surrounded by a single layer of cuboidal cells (fig. 2); (3) Stage 4, oocyte surrounded by two to three cell layers  without antrum formation (fig. 3); (4) Stage  5-6, two or more  layers of cells around oocytes with the onset of antrum formation (fig. 4); (5) Stage 7-8,  oocyte with cumulus oophorus and corona radiata surrounded by a distinct antrum (fig. 5); (6) atretic follicles were also counted and were considered degenerating  when pyknotic nuclei  formed  a  distinct  layer on the inner boundary of granulosa cells (fig. 6). The presence of these pyknotic cells in any stage caused it to be placed in the atretic class.  Stage  2 follicles  exhibited no label and were not counted in total oocyte determinations"

From Taber's
3 types
primary follicle - oogonium and single layer of follicular cells
growing follicle - multiple layers of follicular cells and first maturation of division occurs
vesicular or graafian follicle - posses a cavity (antrum) containing follicular fluid with the oocyte sitting within the cumulus oophorus (mass of cells on the inner surface)

General agreement that antral/vesicular/graafian follicles are defined by the presence of antra/cavities

The MP term has the definitions "any structural anomaly in the ovarian follicle in which the primary oocyte attains its full size and is surrounded by an extracellular glycoprotein layer (zona pellucida) that separates it from a peripheral layer of follicular cells permeated by one or more fluid-filled antra; the primary oocyte occupies the cumulus oophorus while the theca of the follicle develops into internal and external layers"
Fits the definitions I find of antral/vesicular/graafian follicles 

I think the issue may be the use of "secondary" in the label. 

Looking in Uberon I find secondary ovarian follicle (http://purl.obolibrary.org/obo/UBERON_0000036) with the definition "A maturing ovarian follicle that has two more more layers of granulosa cells, up to the onset of antrum formation." This does not agree with the MP definition for this term.

tertiary ovarian follicle (http://purl.obolibrary.org/obo/UBERON_0000037) has the definition "A follicle that has reached the most mature stage of folliculogenesis, characterized by the presence of the antrum." this seems to match the definition in the MP.

Planned resolution:
Change the label on the existing term to match the definition
Add a new term for secondary ovarian follicles
Once the new term is in review and update annotations

**Comment by sbello** [comment]
Also needed to review and update primary, primordial terms to align with Uberon

**Comment by anna-anagnostop** [comment]
Need to update the number definitions to comply with the morph definitions

Add terms for abnormal/increased/decreased secondary ovarian follicle number

**Comment by anna-anagnostop** [comment]
Following discussion with Sue:

- Pre-ovulatroy ovarian follicles should be annotated to “abnormal mature ovarian follicle morphology MP:0009364”

- abnormal growing ovarian follicle morphology has been removed from under abnormal secondary ovarian follicle morphology and is now a narrow synonym of parent term abnormal ovarian follicle morphology MP:0001131 

- Label for abnormal theca folliculi MP:0009365 has been changed to abnormal theca cell layer morphology using abnormal theca folliculi morphology as an exact synonym; MP:0009365 is now a direct child of abnormal ovarian follicle morphology MP:0001131 and its definition has been amendd

- abnormal theca cell number MP:0009369 and its child terms are now placed under abnormal theca cell layer morphology    MP:0009365

**Comment by anna-anagnostop** [comment]
Reopened issue to add "abnormal growing ovarian follicle number" and "absent growing ovarian follicles" as **narrow** synonyms of abnormal ovarian follicle number MP:0008871 and absent ovarian follicles MP:0002777, respectively, as these were still used as exact synonyms of relevant secondary ovarian follicle number terms.
