### ISSUE TITLE
behavioral development

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#953]
We may want to add a branch for the development or maturation of behavior. In J:172361 many of the phenotypes are either late appearance or late disappearance of behaviors and reflexes. Even a general term of behavioral developmental delay might be helpful for grouping these types of phenotypes. Currently I am annotating to the relevant behavior (i.e. abnormal placing response for a delay in the appearance of the placing response).

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/953](https://sourceforge.net/p/obo/mammalian-phenotype-requests/953)

**Comment by sbello** [comment]
closing this as it duplicates #3504
