### ISSUE TITLE
in/decreased size vs enlarged/small, etc

### ISSUE THREAD

**Issue by obophenotype-user** [mgijax/mammalian-phenotype-ontology#956]
Some terms in MP have primary term name of "enlarged X" and may or may not have "increased X size" as a synonym.
Other terms in MP have primary term name of "increased X size" and may or may not have "enlarged X " as a synonym.

A similar situation exists for decreased and small in term names.  

This should be reconciled; at a minimum the appropriate synonyms should be added to all terms.

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/956](https://sourceforge.net/p/obo/mammalian-phenotype-requests/956)

**Comment by sbello** [comment]
Reviewing size terms
